### ISSUE TITLE
HepNodeID unable to have 0 at the beginning

### ISSUE THREAD

**Issue by PNRxA** [sipcapture/heplify#100]
I want to be able to set the HepNodeID to the length of an IP address e.g: 052045123123 (XXX.XXX.XXX.XXX)

I get this error:

```
systemd[1]: heplify.service: main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: heplify.service: control process exited, code=exited status=1
systemd[1]: Unit heplify.service entered failed state.
kill[5418]: kill: failed to parse argument: ''
```

I believe this is due to having a 0 in front of the int (as it works with other numbers there)
It's not a big issue and I don't know if this is viable but is it possible to allow the Node ID to have 0s at the front?

**Comment by negbie** [comment]
Hi Peter,
yes it's because of int/uint type. Mby you can open an issue here https://github.com/sipcapture/HEP and ask for a new octet-string HEP field for something like a hostname.
