### ISSUE TITLE
Building for ARM

### ISSUE THREAD

**Issue by bryanredeagle** [sipcapture/heplify#101]
I'm attempting to build for the Raspberry Pi from my Macbook. Heplify compiles fine when I build for Mac, but when I switch it to linux/armv7, it throws the same error as in the [MIPS issue](https://github.com/sipcapture/heplify/issues/23).

`sniffer/afpacket_linux.go:17:11: undefined: afpacket.TPacket`

The Raspberry Pi seems to have a much older version of go so I thought I would build it on my Mac. Any tips for cross compiling it?

Thanks!

**Comment by bryanredeagle** [comment]
I got this working myself. I needed to use the latest gopacket and freecache. It then compiled fine.

**Comment by lmangani** [comment]
Good to hear you got this sorted! :)
