### ISSUE TITLE
Heplify client crash

### ISSUE THREAD

**Issue by pnlsantos** [sipcapture/heplify#106]
Hi, it takes more time but heplify crash again 

OS: centOS 6
Heplify client 1.47

  2 bash                                                                                                                                                                          $
github.com/negbie/heplify/decoder.correlateRTCP(0xc4255d60bc, 0x4, 0x7b, 0x151d, 0xc4255d60c0, 0x4, 0x77, 0x151d, 0xc4255d60cc, 0x6b, ...)
        /go/src/github.com/negbie/heplify/decoder/correlator.go:95 +0x5f
github.com/negbie/heplify/decoder.(*Decoder).processTransport(0xc4255cc0c0, 0x7f0bb83452f0, 0x7f0bb83460e0, 0x7f0bb8346640, 0x1, 0x4, 0x4, 0xfdc7c70a, 0x0, 0xfdc7c70a, ...)
        /go/src/github.com/negbie/heplify/decoder/decoder.go:318 +0x899
github.com/negbie/heplify/decoder.(*Decoder).Process(0xc4255cc0c0, 0xc4255d60a0, 0x97, 0x97, 0xc4269ba320)
        /go/src/github.com/negbie/heplify/decoder/decoder.go:200 +0xb99
github.com/negbie/heplify/sniffer.(*MainWorker).OnPacket(0xc4200a4980, 0xc4255d60a0, 0x97, 0x97, 0xc4269ba320)
        /go/src/github.com/negbie/heplify/sniffer/sniffer.go:72 +0x59
github.com/negbie/heplify/sniffer.(*SnifferSetup).Run(0xc4201688f0, 0x7f0bb812d3f8, 0xc4201688f0)
        /go/src/github.com/negbie/heplify/sniffer/sniffer.go:312 +0x571
main.main()
        /go/src/github.com/negbie/heplify/main.go:110 +0xde

**Comment by negbie** [comment]
Is this the complete trace. It seems some information are missing.

**Comment by negbie** [comment]
Close because no further info from creator.
