### ISSUE TITLE
Ability to send to multiple heplify-server servers for a HA setup

### ISSUE THREAD

**Issue by PNRxA** [sipcapture/heplify#109]
Is it possible to enter multiple IP addresses for the -hs flag?
We have a highly available solution using Prometheus but the SIP metrics can only be sent to one heplify-server. 
Is there any way to set up a highly available heplify-server currently?

**Comment by negbie** [comment]
Hi Peter,
currently this is not implemented but I can look into it. May I ask you more about your HA solution? Do you have a HA solution only for metrics? Do you use promxy too?

**Comment by PNRxA** [comment]
It's pretty basic with 2 clustered Alertmanagers and 2 Prometheus servers which talk to both Alertmanagers.

Both Prometheus servers scrape the same metrics and have separate databases. There is also a Grafana server for each Prometheus for now. In the future I'll use promxy/haproxy/Thanos to send from both Prometheus servers to a single Grafana.

I'm scraping the same heplify-server with both Prometheus servers but I'd like to be able to send SIP packets to two in case one goes down

**Comment by negbie** [comment]
Ah cool. We are using promxy/Thanos/trickster. Btw. with latest commit https://github.com/sipcapture/heplify/commit/f3c4de82fe689505c39fc18007e14d669554fc60 multiple server (comma separated) can be defined. Keep in mind that  -nt   Network types will be used for all of them.

**Comment by negbie** [comment]
Is it ok for you to build from source or should I publish a new release?

**Comment by PNRxA** [comment]
Awesome, thanks for pumping that out so quickly, can't wait to try it out.

I also haven't heard of trickster before but it looks very cool, I'll definitely look into that.

I'm not sure if it's in this repo but I'm using the heplify with support for the 3CX bridge traffic currently, is it possible to get a build with 3CX bridge support?

**Comment by negbie** [comment]
I hope I have a backup of my work for that ;) Right now I can't find it anymore.

**Comment by PNRxA** [comment]
Ah unfortunately I can't use heplify without the 3CX support as all of our PBXs are 3CX and a significant portion of the traffic is using the bridge

**Comment by negbie** [comment]
@PNRxA can give me a email address from you?

**Comment by PNRxA** [comment]
github@pnrxa.com

**Comment by PNRxA** [comment]
@negbie were you able to find a backup of your work?

**Comment by negbie** [comment]
@PNRxA Sadly not so it will take a while till I find some spare time or a longer train ride ;)

**Comment by PNRxA** [comment]
No problem, the existing agent is working perfectly fine for the time being, appreciate adding the HA option regardless

**Comment by negbie** [comment]
Hi @PNRxA ,
could you please build and test the latest master code? This is only a small part of the decoding code I wrote before but I think it should be enough for your usecase.

**Comment by negbie** [comment]
I hope this will do it for you because it's very unlikely that I will find this year the time to write the full decoder again.

**Comment by PNRxA** [comment]
Thanks @negbie ,

I'll test it out and see how it goes in a few days. Thanks a tonne, appreciate the work

**Comment by PNRxA** [comment]
Just an update, so far it's working great. Both with the decoded packets and the HA. You can probably close this and make a separate issue for the decoder if you plan on working on it later. 

Thanks again for implementing both of these features
