### ISSUE TITLE
panic: runtime error  heplify386

### ISSUE THREAD

**Issue by gudge25** [sipcapture/heplify#11]
[root@goip16 heplify-0.85]# ./heplify386 -i eth0 -hs 144.76.173.89:9060 &
[1] 336
[root@goip16 heplify-0.85]# jobs
[1]+  Running                 ./heplify386 -i eth0 -hs 144.76.173.89:9060 &
[root@goip16 heplify-0.85]# panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaac74b]

goroutine 11 [running]:
sync/atomic.LoadUint64(0x11654824, 0xc3c846, 0x4)
        /usr/lib/go/src/sync/atomic/asm_386.s:159 +0xb
github.com/coocood/freecache.(*Cache).EntryCount(0x11654000, 0xc0ca28, 0xc5af7d)
        /go/src/github.com/coocood/freecache/cache.go:114 +0x51
github.com/negbie/heplify/decoder.(*Decoder).printSIPCacheStats(0x1156a000)
        /go/src/github.com/negbie/heplify/decoder/util.go:86 +0x29
github.com/negbie/heplify/decoder.(*Decoder).printStats.func1(0x1156a000)
        /go/src/github.com/negbie/heplify/decoder/util.go:107 +0x2e
created by github.com/negbie/heplify/decoder.(*Decoder).printStats
        /go/src/github.com/negbie/heplify/decoder/util.go:110 +0x70
^C
[1]+  Exit 2                  ./heplify386 -i eth0 -hs 144.76.173.89:9060
[root@goip16 heplify-0.85]#

**Comment by negbie** [comment]
Let me check. I hope I can find a 32 bit machine. Year ago I was working with one ;)

**Comment by negbie** [comment]
Made a new build
https://github.com/sipcapture/heplify/releases/download/0.9/heplify386

**Comment by negbie** [comment]
One question, did this happen after about 1 minute?

**Comment by gudge25** [comment]
yes 2-3 min

**Comment by negbie** [comment]
Whats about the latest version?

**Comment by negbie** [comment]
I patched out the stats which causes this on 32bit machine

**Comment by gudge25** [comment]
working

**Comment by negbie** [comment]
Pewh harder than expected ;)
