### ISSUE TITLE
heplify and heplify-server - no RTP

### ISSUE THREAD

**Issue by shahabrostami** [sipcapture/heplify#110]
I've currently manually installed heplify (https://github.com/sipcapture/heplify) and heplify-server (https://github.com/sipcapture/heplify-server/) components. Outside of this I do not have any other components installed within the 'sipcapture' space. It seems to be working correctly and I've managed to push SIP related metrics to prometheus. 

Unfortunately it doesn't seem to be capturing anything specific to RTP (heplify is configured with `-m SIPRTP`). It seems to capture the UDP packets but I'm unsure whether it is correctly identifying the RTP ports from the SDP. I've had some trouble following the debug.

`2019/06/04 16:19:15.515472 util.go:111: INFO Packets since last minute IPv4: 343, IPv6: 0, UDP: 343, TCP: 0, RTCP: 5, RTCPFail: 0, DNS: 0, duplicate: 0, fragments: 0, unknown: 0
`

I guess I wanted to confirm whether I should be expecting specific "heplify_rtp" related metrics or only RTCP? 

Thanks

**Comment by lmangani** [comment]
Only RTCP statistics should be expected. The RTP analytics part is much more intensive and currently still only available in the QXIP commercial stack.

**Comment by shahabrostami** [comment]
Understood, thanks for the quick response. 

Can I ask what the difference is between the modes SIPRTP and SIPRTCP if RTP is not part of the analytics?

I will look at the QXIP commercial stack, thanks.

**Comment by negbie** [comment]
@shahabrostami please just use SIPRTCP. SIPRTP is an leftover from an internal branch where I tested go plugins https://golang.org/pkg/plugin/ and integrated played with voipmonitors calculate_mos_fromrtp
https://github.com/voipmonitor/sniffer/blob/develop/rtp.h#L26
Since this only works on linux and feel it's ready to be released.

**Comment by shahabrostami** [comment]
Noted, I think seeing the mode option SIPRTP is what made me hopeful in that some RTP analytics may also be provided. But I am not surprsied at all to learn they are not - as @lmangani mentioned they are much more intensive.

Thanks for the explanation.

**Comment by maohsiang** [comment]
> @shahabrostami please just use SIPRTCP. SIPRTP is an leftover from an internal branch where I tested go plugins https://golang.org/pkg/plugin/ and played with voipmonitors calculate_mos_fromrtp
> https://github.com/voipmonitor/sniffer/blob/develop/rtp.h#L26
> Since this only works on linux I don't think it's ready to be released.

hi @negbie You mention it works here, could you please clarify what exactly works ?
Do we consider to enable "SIPRTP" to capture RTP in linux host ?
BTW, do we have to config heplify-server to parse the RTP packet ?

**Comment by negbie** [comment]
RTP is only partly implemented in the oss version. If you are working for a non profit organisation which helps humans in any way you can reach me via mail and we can disscuss about heplify-rtp otherwise feel free to contact qxip.
