### ISSUE TITLE
heplify 1.46 windows crashing

### ISSUE THREAD

**Issue by astrakid** [sipcapture/heplify#115]
using heplify 1.46 on windows, getting the following output as soon as a sip-packet arrives:

```
E:\monitoring\heplify_latest>heplify -hs 10.100.18.126:9060 -wf e:\monitoring\heplify_latest\ -i \Device\NPF_{26BAD500-9A73-494D-9387-3679462B0C97}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5fffc3]


goroutine 37 [running]:
github.com/negbie/heplify/dump.Save(0xc000042060, 0x1)
        C:/Users/negbiegaming/go/src/github.com/negbie/heplify/dump/dump.go:119 +0x713
created by github.com/negbie/heplify/sniffer.New
        C:/Users/negbiegaming/go/src/github.com/negbie/heplify/sniffer/sniffer.go:193 +0x1ff


E:\monitoring\heplify_latest>heplify -hs 10.100.18.126:9060 -wf e:\monitoring\heplify_latest\ -i \Device\NPF_{26BAD500-9A73-494D-9387-3679462B0C97}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5fffc3]


goroutine 12 [running]:
github.com/negbie/heplify/dump.Save(0xc0005e8120, 0x1)
        C:/Users/negbiegaming/go/src/github.com/negbie/heplify/dump/dump.go:119 +0x713
created by github.com/negbie/heplify/sniffer.New
        C:/Users/negbiegaming/go/src/github.com/negbie/heplify/sniffer/sniffer.go:193 +0x1ff
```

It is a virtual machine under vmware 6.7, OS windows 2016.

```
E:\monitoring\heplify_latest>heplify -hs 10.100.18.126:9060 -wf e:\monitoring\heplify_latest\
-i \Device\NPF_{26BAD500-9A73-494D-9387-3679462B0C97} (VMware vmxnet3 virtual network device)


Critical: <nil> -i any is not supported on windows
Please use one of the above devices
```

**Comment by astrakid** [comment]
error occured because of missing permissions (have to run the cmd as administrator).

**Comment by astrakid** [comment]
no issue of heplify.

**Comment by negbie** [comment]
Hi @astrakid 
Thanks for figuring out. Do you think I can improve something. Error message or something like that so it's more obvious for the user?

**Comment by astrakid** [comment]
hi,
if it was a permission thing, error message like "need higher permissions" or anything similar would help, but in this case (as i commented already in googlegroup) my test was faulty, it still doesn't work.
regards,
andre

**Comment by negbie** [comment]
Some error or something else? Could you please paste the error message?

**Comment by astrakid** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5fffc3]

goroutine 10 [running]:
github.com/negbie/heplify/dump.Save(0xc000092180, 0x1)
        C:/Users/negbiegaming/go/src/github.com/negbie/heplify/dump/dump.go:119 +0x713
created by github.com/negbie/heplify/sniffer.New
        C:/Users/negbiegaming/go/src/github.com/negbie/heplify/sniffer/sniffer.go:193 +0x1ff

**Comment by negbie** [comment]
Ok thanks. Will need to spin up a win vm and try to reproduce.

**Comment by adubovikov** [comment]
I am still thinking that it something with access to interfaces. If you run it on normal hardware can you see same error ?

**Comment by astrakid** [comment]
i have currently no real hardware here with sufficient permissions and pcap installed.

**Comment by negbie** [comment]
ok created a win vm and tried to reproduce but so far I can't. You have write permission to that folder right?

**Comment by negbie** [comment]
let me test it with some fake traffic.

**Comment by negbie** [comment]
Found it. You are already using NPcap which prints the devicenames with some backslashes. I create a tmp file with the device name and the backslashes caused your troubles. As a goodie I uploaded a recent windows version for you ;)

**Comment by negbie** [comment]
And I would alwas recommend you to quote your path flags like -wf "e:\monitoring\heplify_latest\"

**Comment by astrakid** [comment]
perfect, you are the greatest!!

**Comment by negbie** [comment]
Your welcome. Please test and close here when everything works. Thanks.

**Comment by negbie** [comment]
https://github.com/sipcapture/heplify/releases
heplify.exe

**Comment by astrakid** [comment]
works like a charm!!! thanks a lot eugen!

**Comment by adubovikov** [comment]
thanks guys
