### ISSUE TITLE
Not compiled

### ISSUE THREAD

**Issue by changzx** [sipcapture/heplify#122]
dear:
     When I compile heplify1.52, I have the following error:
```
/root/gowork/pkg/mod/github.com/google/gopacket@v1.1.18-0.20190620071746-836b571ec913/pcap/pcap_unix.go:34:18: error: pcap.h: No such file or directory
/root/gowork/pkg/mod/github.com/google/gopacket@v1.1.18-0.20190620071746-836b571ec913/afpacket/header.go:178:103: could not determine kind of name for C.sizeof_struct_tpacket3_hdr
```
    Looking forward to your recovery！

**Comment by negbie** [comment]
Hi,
whats your os?

**Comment by changzx** [comment]
> Hi,
> whats your os?

CentOS Linux release 7.6.1810 (Core)

**Comment by negbie** [comment]
What does this command print?
whereis pcap

**Comment by changzx** [comment]
> What does this command print?
> whereis pcap

![1567073859(1)](https://user-images.githubusercontent.com/42836671/63932218-57919600-ca89-11e9-9762-8aac5223cc1d.jpg)

**Comment by negbie** [comment]
Do you have libpcap-dev installed?

**Comment by changzx** [comment]
![1567082934(1)](https://user-images.githubusercontent.com/42836671/63941544-75b5c100-ca9e-11e9-9ddb-dda27378749b.jpg)

**Comment by negbie** [comment]
Ok now install libpcap-devel.

**Comment by changzx** [comment]
> libpcap-devel.
OK， libpcap-devel has been install. but:
![1567133651(1)](https://user-images.githubusercontent.com/42836671/63989952-c9fb8800-cb14-11e9-8abe-d27b9c6c5e82.png)

**Comment by negbie** [comment]
Ok the error about not finding pcap.h is gone. Now make sure that you have at least Go 1.11 installed.

**Comment by changzx** [comment]
> Ok the error about not finding pcap.h is gone. Now make sure that you have at least Go 1.11 installed.

go version go1.12.7 linux/amd64

**Comment by negbie** [comment]
Which kernel version do you have?

**Comment by changzx** [comment]
> Whats your os kernel version? I think you have some old linux headers.

It's OK!

**Comment by changzx** [comment]
> Whats your os kernel version? I think you have some old linux headers.

Thank you!
