### ISSUE TITLE
heplify Port usage

### ISSUE THREAD

**Issue by changzx** [sipcapture/heplify#123]
hello:
    After the heplify starts, it takes up a random UDP port. Can I fix the port?
![1567138675(1)](https://user-images.githubusercontent.com/42836671/63992812-43e53e80-cb20-11e9-9da5-f91cc9050f5c.jpg)

**Comment by negbie** [comment]
No.

**Comment by negbie** [comment]
If you really need this you need to change the code.

**Comment by changzx** [comment]
> If you really need this you need to change the code.

Can you tell me where I need to change?

**Comment by negbie** [comment]
https://github.com/sipcapture/heplify/blob/master/publish/hep.go#L65
or 
https://github.com/sipcapture/heplify/blob/master/publish/hep.go#L69

depending if you use UDP or TCP replace the dial call with DialUDP or DialTCP. If you need more context you can find all the things you need here:

https://golang.org/pkg/net/#DialUDP
https://golang.org/pkg/net/#DialTCP

**Comment by changzx** [comment]
> If you really need this you need to change the code.



> https://github.com/sipcapture/heplify/blob/master/publish/hep.go#L65
> or
> https://github.com/sipcapture/heplify/blob/master/publish/hep.go#L69
> 
> depending if you use UDP or TCP replace the dial call with DialUDP or DialTCP. If you need more context you can find all the things you need here:
> 
> https://golang.org/pkg/net/#DialUDP
> https://golang.org/pkg/net/#DialTCP

Thank you!
