### ISSUE TITLE
-dim is not applied to -wf pcap

### ISSUE THREAD

**Issue by gmaruzz** [sipcapture/heplify#125]
the -dim option can be used to filter out (eg, to not act on) some kins of methods (OPTIONS, NOTIFY, etc)

it works well as per the hep packets sent to the homer server, they are not sent for filtered out methods

it does not work for the packets written in the saved pcap created by the -wf option

you can verify this with a command string like:

/usr/local/bin/heplify -m SIP -hs 192.168.1.1:9060 -wf /var/log/tcpdump/ -rt 10 -dim OPTIONS

you will see that OPTIONS method packets are not sent to homer server (correct), but they are written in the saved pcap (incorrect)

thanks a lot for your work, very very appreciated!

**Comment by negbie** [comment]
Hi,
which heplify version do you use? If I remember it right I've changed the logic in version >= 1.4

**Comment by gmaruzz** [comment]
Hi Eugen, thank for your reply!

I am using version 1.47

**Comment by negbie** [comment]
Ah sorry now I know why. The dim flag is handled inside the decoder and not in the sniffer. Thats why you see these packets. I think I did it this way because I wanted more flexibility.

You can use the -di flag. This is inside the sniffer and should filter out every packet before it goes into the pcap.

For example:

-di " OPTIONS\r\n"

**Comment by gmaruzz** [comment]
understood, thanks.
I will try to use 
-di "sip\ OPTIONS"
or something on these lines

**Comment by negbie** [comment]
Try exaclty -di " OPTIONS\r\n"
This is because the -di flag does not parse the CSEQ header. Would you only use -di "OPTIONS" you could get a match from the Allow header and filter out wrong packets.

**Comment by negbie** [comment]
-di " OPTIONS\r\n" is the end of CSeq line for OPTIONS

**Comment by gmaruzz** [comment]
works perfect, thank you!
