### ISSUE TITLE
heplify memory usage

### ISSUE THREAD

**Issue by changzx** [sipcapture/heplify#126]
Dear:
   How much is the heplifymemory usage?

**Comment by negbie** [comment]
Depends on the amount of traffic and the flags you use (dedup, tcp ....) I would say from 100MB to 20GB RAM.

**Comment by changzx** [comment]
> Depends on the amount of traffic and the flags you use (dedup, tcp ....) I would say from 100MB to 20GB RAM.

i use udp
./heplify -i eth0 -p /data/hep/log -hs 192.168.100.111:9060

**Comment by negbie** [comment]
shouldn't be that high. Mby 1GB. Never measured it. The smallest server I'm working with starts with 128GB so even 1GB is so far down in top output that I never payed attention to it.

**Comment by negbie** [comment]
@changzx will close this. When you have further questions regarding this topic just update this issue.

**Comment by shaneqld** [comment]
Would you please share any guidance to reducing the memory footprint of heplify-server?

In my use case, I'm receiving HEP over UDP and the sole purpose of heplify-server is to write this data to postgres (and drop old data from the db periodically).  heplify-server is running in Kubernetes where I need to define memory limits.

At about 1500 PPS, heplify-server memory usage grows linearly over time to use about 2GB memory (the maximum I have allowed for now) over 40 minutes before it is OOMKilled.

I'm very curious at to what is being stored in memory to cause it to grow over time. Is there any functionality that can be disabled to reduce the amount of things stored in memory for this use case?

Thanks in advance
