### ISSUE TITLE
Modify to a specific port

### ISSUE THREAD

**Issue by changzx** [sipcapture/heplify#130]
Dear:
   I want to modify to a specific port use UDP or TCP replace the dial call with DialUDP or DialTCP.
DialUDP Request for  "raddr *UDPAddr",  but address string in the Dial。I can only set the destination address to specific now. Can you help me?
![image](https://user-images.githubusercontent.com/42836671/66474688-5c079080-eac4-11e9-89d4-b695b461740f.png)

**Comment by lmangani** [comment]
What is the purpose of your change? I fail to understand it.

**Comment by negbie** [comment]
I've already told you what you have to do:
https://github.com/sipcapture/heplify/issues/123

This is to specifiy for the most users so, please go ahead, fork it and made your change.

**Comment by negbie** [comment]
This change is quite trivial but not generic enough to implement it for all. If you are not able to do this yourself, please write support@sipcapture.org and ask for an offer.

**Comment by negbie** [comment]
As a hint I can tell you that DialUDP and DialTCP need
*net.UDPAddr and *net.TCPAddr to get them you can use

tcpAddr, err := net.ResolveTCPAddr("tcp", "YOUR ADDRESS")
udpAddr, err := net.ResolveUDPAddr("udp", "YOUR ADDRESS")

**Comment by changzx** [comment]
> As a hint I can tell you that DialUDP and DialTCP need
> *net.UDPAddr and *net.TCPAddr to get them you can use
> 
> tcpAddr, err := net.ResolveTCPAddr("tcp", "YOUR ADDRESS")
> udpAddr, err := net.ResolveUDPAddr("udp", "YOUR ADDRESS")

thank you!
