### ISSUE TITLE
How to specify the listening interface for multiple NIC bindings

### ISSUE THREAD

**Issue by changzx** [sipcapture/heplify#136]
dear:
 How to specify the listening interface for multiple NIC bindings

**Comment by negbie** [comment]
either heplify -i any or
heplify -i mau
heplify -i maumau
heplify -i maumaumau
heplify -i maumaumaumau

**Comment by negbie** [comment]
dont forget to put & at the end

**Comment by changzx** [comment]
> dont forget to put & at the end

like this?
./heplify -i eth0 eth1

**Comment by negbie** [comment]
No thats not possible more like this:

./heplify -i eth0 &
./heplify -i eth1 &

Spawns two heplify processes.
