### ISSUE TITLE
Too many colons in addres

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/heplify#137]
Hello,

following the Readme i tried to set two destinations in hs, but i'm returned : 

Critical: dial tcp: address 10.16.0.95:9060,10.21.0.95:9060: too many colons in address

Is there a trick to make it work or should i consider to start a second service ? 

Regards

David

Ps:  version 1.47

**Comment by negbie** [comment]
Hi,
ups I just saw that the latest release 1.47 is from 8 Dec 2018. Damn, time flies by way to fast :) Published latest release 1.52 which should have the feature you are looking for.
