### ISSUE TITLE
multiple heplify-server

### ISSUE THREAD

**Issue by changzx** [sipcapture/heplify#138]
Dear:
  If we want to forward to multiple heplify-server addresses, can we add nginx to the heplify-server front end?

**Comment by negbie** [comment]
I'm not sure if I understand you in the right way. Nginx has nothing to do with this. It's a webserver, reverse proxy mainly for HTTP. heplify sends HEP messages. HEP!=HTTP.

So the only thing you want so to send from heplify to multiple destinations? Try this:

./heplify -hs "192.168.1.1:9060,192.168.2.2:9060"

Make sure you use the latest version 1.52.

**Comment by changzx** [comment]
> I'm not sure if I understand you in the right way. Nginx has nothing to do with this. It's a webserver, reverse proxy mainly for HTTP. heplify sends HEP messages. HEP!=HTTP.
> 
> So the only thing you want is to send from heplify to multiple destinations? Try this:
> 
> ./heplify -hs "192.168.1.1:9060,192.168.2.2:9060"
> 
> Make sure you use the latest version 1.52.

./heplify -hs "192.168.1.1:9060,192.168.2.2:9060"
In fact, is it open two heplify clients?

**Comment by negbie** [comment]
It's one heplify process which sends packets to two different heplify-server. Just try it out ;)
