### ISSUE TITLE
No capture of traffic on Asterisk

### ISSUE THREAD

**Issue by homertester** [sipcapture/heplify#14]
Dear,

I'm running the FreePBX Distro, running Asterisk 13.17.2.

I tried capturing & sending the voice traffic to our HOMER server, but we didn't see any traffic flowing.

Command we used:
./heplify -i eth0 -hs ip:9060 -t af_packet -m SIPRTCP -l debug -pr 5060-5061

What could be causing this?

Thanks for your help

**Comment by negbie** [comment]
Do you see something in the logs. You can append -e . This will print the infos into console.
You can also try without af_packet like:

./heplify -i any -hs ip:9060 -m SIPRTCP -l debug -pr 5060-5061 -e

**Comment by negbie** [comment]
Btw. since heplify 0.9 -m SIPRTCP is the default so you don't need to specify it.

**Comment by homertester** [comment]
Hello Negbie,

FYI: If you specify "-i any" > I need to add "-t af_packet" as option as well.

Full command I'm using now: ./heplify -i any -hs 91.236.244.114:9060 -l debug -pr 5060-5061 -e -t af_packet

Then I indeed see output into the console. It also looks like I have some data in Homer now... but it has a big delay.

When checking a specific call ID, I see : "Sorry! No Statistics Available!"

**Comment by negbie** [comment]
Ok thats good so far. Have both servers ntp enabled?

**Comment by negbie** [comment]
"FYI: If you specify "-i any" > I need to add "-t af_packet" as option as well."
Do you use the latest Version. I fixed the LinkTypeLinuxSLL link type in Version 0.90 so -i any should work with and without -t af_packet.

Btw instead of using -l debug you can use debug selectors with -d like:

-d payload,rtcp,fragment

**Comment by negbie** [comment]
And heplify has a dry run mode to show you what it would send to homer. Use it with -hs "" in your case:

./heplify -i any -hs "" -pr 5060-5061 -t af_packet -e

**Comment by negbie** [comment]
But blindly guessed I would say your ntp setup is not correct ;)

**Comment by negbie** [comment]
You are 2 versions behind ;) You use 0.85 in your link. Try with:

**Comment by negbie** [comment]
Another tip, use:
./heplify -i any -hs "" -pr 5060-5061 -t af_packet -e

stop it and right after paste 
date +%s
into console. This will give you the unixtime stamp. You can compare Tsec with the one date +%s
produces.

**Comment by negbie** [comment]
I just tested it and on all my Servers I see:
  "Host": "sniffersvp",
  "HEPType": 1,
  "Tsec": 1512579335,
  "Tmsec": 235452,
....

# date +%s
1512579336

**Comment by homertester** [comment]
"Host": "hostname",
  "HEPType": 1,
  "Tsec": 1512579606,
  "Tmsec": 382512,

^C
[root@hostname ~]# date +%s
1512579607

**Comment by negbie** [comment]
Ok that looks good. So heplify does its job. It must be on the other side.

**Comment by negbie** [comment]
Now you can check if you have the right timestamps in the db. Check if you have the right timezone selected in the homer gui. But all this shouldn't be heplify related as it captures the packets with the right timestampts.

**Comment by homertester** [comment]
Need to go right now... will check this later, sorry.

**Comment by negbie** [comment]
No problem. Tell me if you need more help.
