### ISSUE TITLE
no data on server

### ISSUE THREAD

**Issue by pnlsantos** [sipcapture/heplify#140]
Hello since i update heplify client to 1.52 i have no data on homer 5.
the table sip_capture_calls_xxx have no entries 

the /var/log/messages on homer 5 show this

Nov 15 11:40:01 voipdiag homer[1193]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:01 voipdiag homer[1190]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:01 voipdiag homer[1194]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:01 voipdiag homer[1191]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:01 voipdiag homer[1192]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:01 voipdiag homer[1193]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:01 voipdiag homer[1190]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:02 voipdiag homer[1194]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:02 voipdiag homer[1192]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:02 voipdiag homer[1191]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:02 voipdiag homer[1192]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Nov 15 11:40:02 voipdiag homer[1192]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Nov 15 11:40:02 voipdiag homer[1191]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Nov 15 11:40:02 voipdiag homer[1191]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Nov 15 11:40:02 voipdiag homer[1193]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:02 voipdiag homer[1193]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Nov 15 11:40:02 voipdiag homer[1193]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Nov 15 11:40:02 voipdiag homer[1190]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:02 voipdiag homer[1190]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Nov 15 11:40:02 voipdiag homer[1190]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Nov 15 11:40:02 voipdiag homer[1190]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:02 voipdiag homer[1192]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:02 voipdiag homer[1190]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Nov 15 11:40:02 voipdiag homer[1190]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Nov 15 11:40:02 voipdiag homer[1192]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Nov 15 11:40:02 voipdiag homer[1190]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Nov 15 11:40:02 voipdiag homer[1192]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Nov 15 11

**Comment by pnlsantos** [comment]
server = homer 5

**Comment by adubovikov** [comment]
please install heplify-server

**Comment by pnlsantos** [comment]
where? i have 23 voip gateways with heplify client sending packets to homer 5 . Do you mean change homer 5 to heplify server ? 
thankyou

**Comment by lmangani** [comment]
Homer 5 is really no longer supported so the path forward in order to get help, fixes and features is to replace the server components with the latest Homer generation, which is right now 7.7 and using heplify-server instead of Kamailio/OpenSIPS for the HEP processing and inserting portions.

**Comment by pnlsantos** [comment]
i will do that. thanks
