### ISSUE TITLE
Handling packets with VXLAN Header

### ISSUE THREAD

**Issue by sharafi1981** [sipcapture/heplify#141]
Hi Eugen,

As per your request on Google group, I am opening an issue related to handling packets that are encapsulated with a VXLAN header. (https://groups.google.com/forum/?nomobile=true#!topic/homer-discuss/qXvcIJQpb5w)

I will prepare a pcap and send it you later.

Thanks.

**Comment by negbie** [comment]
Thanks! You can send me the pcap to negbie@posteo.de

**Comment by sharafi1981** [comment]
Eugen,

I have the pcap and I can email you the link to download it. can you please let me know where to send it to?

**Comment by negbie** [comment]
negbie@posteo.de

**Comment by sharafi1981** [comment]
Thanks. Sent.

**Comment by negbie** [comment]
Got it. I will take a look into this when I'm back at home.

**Comment by negbie** [comment]
Hi @sharafi1981 
https://github.com/sipcapture/heplify/commit/9ab36c4d421b2dccf68404c4c89a84afaf8b03bc adds VXLAN support.

**Comment by sharafi1981** [comment]
Perfect, this worked. Thanks Eugen!

**Comment by negbie** [comment]
Happy to hear that ;)
