### ISSUE TITLE
[CenOS 7] Compilation issue

### ISSUE THREAD

**Issue by denyspozniak** [sipcapture/heplify#145]
Hello!
I could not compile **heplify** in CentOS 7 (release 7.7.1908), please check output below:

```
[root@localhost heplify]# make
go build -ldflags "-s -w"  -o heplify *.go
# runtime/cgo
/usr/bin/ld: cannot find -lpcap
collect2: error: ld returned 1 exit status
make: *** [all] Error 2
```
```
[root@localhost heplify]# rpm -qa | grep pcap
libpcap-devel-1.5.3-11.el7.x86_64
libpcap-1.5.3-11.el7.x86_64
```

PS. When I commented string **export CGO_LDFLAGS...** in **Makefile**, Heplify was compiled well.

**Comment by negbie** [comment]
Hi @denyspozniak 
thank you for the hint. Yeah I guess the path to libpcap.a is different on CentOS. I will comment this line in the next release.

**Comment by thiagocpv** [comment]
Hi there
Any news about centOS7?

**Comment by negbie** [comment]
Hi, just fixed it https://github.com/sipcapture/heplify/commit/a4e426dc7c17b2de099fda59bc55ff58db0b0862
