### ISSUE TITLE
[CentOS 6] complaining about libraries 

### ISSUE THREAD

**Issue by donweasel** [sipcapture/heplify#147]
Hello,
trying to run heplify on an old install of Centos6 and FreeSwitch 1.4, bellow the errors

[root@FS_b1 src]# ./heplify -i eth0 -pr 5060-5080 -hs 192.168.10.222:9060
./heplify: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./heplify)
./heplify: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./heplify)

**Comment by negbie** [comment]
Hi, latest release isn't fully static build. Could you please try a previous version. Will staticly build the latest version in the next days.

**Comment by donweasel** [comment]
Hi @negbie which version will work?

thanks

**Comment by donweasel** [comment]
@negbie  this worked... i see traffic now on he HOMER UI  thanks

wget https://github.com/sipcapture/heplify/releases/download/1.47/heplify
