### ISSUE TITLE
./heplify command not available

### ISSUE THREAD

**Issue by vkprabha29** [sipcapture/heplify#158]
hello
i am tryining to execute the heplify command like this to push the traffic to homer and displayed No such file. please can any body tell me the exact directory

./heplify -i eno2 -hs 0.0.0.0:9060

root@hom~/heplify# ./heplify -i eno2 -hs 0.0.0.0:9060
-bash: ./heplify: No such file or directory

**Comment by lmangani** [comment]
Did you `chmod +x` the downloaded binary? If you did, then you're probably using the wrong arch. Please provide details about your OS/Version and the Architecture of your system to get help.

**Comment by vkprabha29** [comment]
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch


root@hom:~# docker images -a
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
<none>                      <none>              a9e27a74881a        37 minutes ago      9.25MB
sipcapture/heplify          latest              a9546562b281        37 minutes ago      9.25MB
<none>                      <none>              d06f9054a0c1        37 minutes ago      584MB
<none>                      <none>              46416841895f        37 minutes ago      233kB
<none>                      <none>              dffcdbf61a40        38 minutes ago      496MB
<none>                      <none>              ffecd1d72b01        38 minutes ago      490MB
<none>                      <none>              4dcaf84bd39e        38 minutes ago      496MB
sipcapture/webapp           latest              0cd872517718        17 hours ago        32.8MB
grafana/loki                master              ab2dbfabebdd        21 hours ago        47.6MB
grafana/grafana             master              d72e5aad0a79        22 hours ago        234MB
postgres                    11-alpine           6d9ed89bf558        33 hours ago        152MB
prom/prometheus             latest              e935122ab143        8 days ago          134MB
golang                      alpine              e1fd9820be16        8 days ago          359MB
sipcapture/heplify-server   master              83e5530f95ad        3 weeks ago         22.2MB
chronograf                  1.5-alpine          ebbefd794b19        4 weeks ago         44.5MB
kapacitor                   1.5-alpine          edbdff6902f9        4 weeks ago         73.6MB
influxdb                    1.5-alpine          7d6f252a585b        4 weeks ago         83.9MB
alpine                      latest              e7d92cdc71fe        5 weeks ago         5.59MB
prom/alertmanager           latest              0881eb8f169f        2 months ago        52.1MB
sipcapture/heplify          master              e70f59ad3fc8        4 months ago        9.25MB
prom/node-exporter          latest              e5a616e4b9cf        8 months ago        22.9MB
sipcapture/hepsub           master              3ef6550c4bc6        9 months ago        90.6MB
telegraf                    1.5-alpine          aa8daabb3b1c        17 months ago       42MB
stefanprodan/caddy          latest              655880563633        2 years ago         24.7MB

root@hom:~# docker container ls
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                    PORTS                                                                                            NAMES
8b10dd05d362        sipcapture/heplify:master          "./heplify -t af_pac…"   51 minutes ago      Up 50 minutes                                                                                                              heplify
2b9c193ebaa6        chronograf:1.5-alpine              "/entrypoint.sh chro…"   55 minutes ago      Up 55 minutes             8888/tcp                                                                                         hom7-influx-tick_chronograf_1
89118d74bd49        kapacitor:1.5-alpine               "/entrypoint.sh kapa…"   55 minutes ago      Up 55 minutes             9092/tcp                                                                                         hom7-influx-tick_kapacitor_1
6d0bee628093        postgres:11-alpine                 "docker-entrypoint.s…"   55 minutes ago      Up 55 minutes (healthy)   5432/tcp                                                                                         hom7-influx-tick_db_1
ae703587a9da        influxdb:1.5-alpine                "/entrypoint.sh infl…"   55 minutes ago      Up 55 minutes             8086/tcp                                                                                         hom7-influx-tick_influxdb_1
13fe9e84de8d        sipcapture/webapp                  "/docker-entrypoint.…"   58 minutes ago      Up 58 minutes                                                                                                              homer-webapp
8a58117e413e        sipcapture/heplify-server:master   "./heplify-server"       58 minutes ago      Up 58 minutes             0.0.0.0:9060->9060/tcp, 0.0.0.0:9060->9060/udp, 9090/tcp                                         heplify-server
a47590cf3351        prom/node-exporter:latest          "/bin/node_exporter …"   58 minutes ago      Up 58 minutes             9100/tcp                                                                                         nodeexporter
ca17be47ab5e        postgres:11-alpine                 "docker-entrypoint.s…"   58 minutes ago      Up 58 minutes (healthy)   5432/tcp                                                                                         db
1821894f62fa        prom/alertmanager:latest           "/bin/alertmanager -…"   58 minutes ago      Up 58 minutes             9093/tcp                                                                                         alertmanager
85658a7bd6da        prom/prometheus:latest             "/bin/prometheus --c…"   58 minutes ago      Up 58 minutes             9090/tcp                                                                                         prometheus
6e41efa9e21c        grafana/grafana:master             "/run.sh"                58 minutes ago      Up 58 minutes (healthy)   3000/tcp                                                                                         grafana
b379934037d2        stefanprodan/caddy                 "/sbin/tini -- caddy…"   58 minutes ago      Up 58 minutes             0.0.0.0:3000->3000/tcp, 0.0.0.0:9080->9080/tcp, 0.0.0.0:9090->9090/tcp, 0.0.0.0:9093->9093/tcp   caddy
6184651657a8        grafana/loki:master                "/usr/bin/loki -conf…"   58 minutes ago      Up 58 minutes             80/tcp, 0.0.0.0:3100->3100/tcp                                                                   loki

**Comment by negbie** [comment]
@vkprabha29 thanks for the info and glad this fixed it.

**Comment by vkprabha29** [comment]
Hello Negbie
Thanks for adivise.

At the moment, i am testing by pushing traffic to homer. But in the homer window, it shows only  200 records.  
1) Could you advise me how to increase the number of showing records.
2) Grafana shows the MOS report. But i am unable to get the value. Please advice me how to get it.
3) using the caller ID, i need to accumulate the trace and export to pcap. But that options is not avilable? Please advise how to do.

Thanks
vkp

**Comment by negbie** [comment]
Hi @vkprabha29 these are very basic questions and doesn't belong into this repo.If you couldn't find answers to them in the homer wiki https://github.com/sipcapture/homer/wiki please open a github issue under the homer repo https://github.com/sipcapture/homer/issues maybe the wiki should be extended and can help other new homer users like you.
