### ISSUE TITLE
Capture Janus Events Log with heplify

### ISSUE THREAD

**Issue by NinoFares** [sipcapture/heplify#161]
Hi guys,

I would like to send Janus events to my heplify-server, can i do it with heplify ? I saw that it supports LOGS Capture.

If it's possible, how can I do it?

Thanx :D.

**Comment by lmangani** [comment]
Short answer: no. You need to use HEPop to handle Janus events, but writes can converge to the same database as `hepflify-server` and under the same HOMER roof.

**Comment by NinoFares** [comment]
Okey, i will try to do that, thanks for your answer !
