### ISSUE TITLE
dropping KDMQ messages

### ISSUE THREAD

**Issue by kpribic** [sipcapture/heplify#162]
heplify 1.56 started with:

```
/opt/heplify/heplify -hs x.x.x.x:9060 -nt tcp -hn webrtc-kam-heplify -dim KDMQ
```
Doesn't appear to drop KDMQ methods. Is dropping this method unsupported?

**Comment by negbie** [comment]
@kpribic I need a pcap to start looking into this.

**Comment by kpribic** [comment]
Can I send it to negbie@posteo.de?

**Comment by negbie** [comment]
Yes please.

**Comment by negbie** [comment]
Added it with commit https://github.com/sipcapture/heplify/pull/163

Did this ever worked? I cannot remember that I ever added KDMQ to ragel. Mby you've used the -di flag before?

**Comment by kpribic** [comment]
I think this never worked, didn't really notice before because there wasn't that much KDMQ traffic.
Give me a minute to confirm this...

**Comment by negbie** [comment]
About your question with mangled json payload. Hard to tell whats going on. If it's important for you it will need more effort to investigate this.

**Comment by kpribic** [comment]
Not important to me at the moment, I want to drop the messages anyway so don't bother for my sake. I was just pointing it out because there was some json logic added to heplify/heplify-server so I figured it may be of interest to you.

I just noticed that there is  `-nt tcp` flag in the heplify command however pcap shows that HEP is going over UDP. That is supposed to go over TCP right?

**Comment by negbie** [comment]
Ok. Yes -nt tcp should go over tcp and if it's not it's a bug.

**Comment by kpribic** [comment]
Tested, works, KDMQ messages are dropped properly. 
Please disregard the TCP comment, I was looking at the wrong part of the trace.
