### ISSUE TITLE
SIP/TLS Support

### ISSUE THREAD

**Issue by Sp0rN** [sipcapture/heplify#166]
Hi Guys,

We recently started terminating calls with a new provider via TLS, I read in another issue that SSL/TLS isn't supported by heplify, is this correct? If so, is there another capture agent I can use to push hep to my Homer stack that supports SIP TLS/SSL?

Thanks.

**Comment by lmangani** [comment]
@Sp0rN unless you are using insecure RSA keys, heplify (or any other agent) cannot and should not be able to decrypt modern DH TLS - or it would be pointless to call it secure :) 

The best and secure way is to terminate your TLS to a HEP supported platform such as Kamailio or OpenSIPS which are able to mirror clear packets without breaking your own security, or use something like [HEPjack](https://github.com/sipcapture/HEPjack.js) to attack the SSL library. I hope this helps!
