### ISSUE TITLE
Help to understand functionality

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/heplify#169]
Trying to understand what the code here does (not really an issue). 

https://github.com/sipcapture/heplify/blob/1b2a80825bf4ef051337a8a746285346c7d992c3/decoder/correlator.go#L27

https://github.com/sipcapture/heplify/blob/1b2a80825bf4ef051337a8a746285346c7d992c3/decoder/correlator.go#L98

As I understand this - the agent will generate a correlation_id which is the Call-ID for the media which belongs to that call-id. 

So for two different call legs (i.e. b2bua scenario), which each have different call-IDs, this generates two unique 'correlation-id' for those RTCP streams that are sent to heplify-server, yes?

**Comment by lmangani** [comment]
Yes. That's correct and this should be addressed in the correlation logic of HEPIC to stitch them back together.
