### ISSUE TITLE
Separating SIP from RTCP

### ISSUE THREAD

**Issue by stephanomarques** [sipcapture/heplify#177]
By default the heplify-agent sends SIP+RTCP traffic to the heplify-server. Can this be modified (i.e the -m capture mode option) to capture SIP or RTCP ? I don't see an option to pick one or the other, because this would be useful for the solution I have setup.

**Comment by lmangani** [comment]
@stephanomarques is `-m SIP` not working for you? RTCP without SIP would have no correlation so it makes little sense unless I'm missing the point. Note heplify is designed to be simple so If you need advanced routing options, look into captagent which offers this behaviour more flexibly.
