### ISSUE TITLE
HEPlify Agent for Windows 10 64bit

### ISSUE THREAD

**Issue by andyegli** [sipcapture/heplify#182]
Hi 

I would like to ask for some advice how to get the latest heplify agent going on Windows 10 64bit and/or Windows Server 2016 64bit. I have installed GO and downloaded the source and unsure how to compile for the above platforms. 

Andy

**Comment by negbie** [comment]
First install Winpcap or Npcap (I would suggest npcap), then go into the source folder and type go build. Paste your errors along the way here. Mby it can help others!

**Comment by andyegli** [comment]
Thank you negbie worked.
Sometimes silly where you can get stuck.
