### ISSUE TITLE
DTMF Capture

### ISSUE THREAD

**Issue by Sp0rN** [sipcapture/heplify#184]
Hi Guys,

Im trying to diagnose a few DTMF issues I have, but I cannot seem to pickup any DTMF info in any of my HOMER data.

Are their specific flags required for the heplify binary to capture DTMF alongside SIP/RTCP?

**Comment by negbie** [comment]
Hey, it's just not implemented.

**Comment by Sp0rN** [comment]
Thanks Eugen.
