### ISSUE TITLE
Unable to correlate RTCP with Asterisk and endpoint NAT=yes

### ISSUE THREAD

**Issue by Demolish50** [sipcapture/heplify#188]
Debugging RTCP shows "DBG [rtcp] No correlationID" with heplify debug turned on.

Looking at the PCAP I can see that heplify is unable to correlate the RTCP stream due to the srcip being different in the SDP body. I learned this from "https://github.com/sipcapture/heplify/issues/76"

Here is the configuration.

- Asterisk server outside of NAT.
- Phones inside NAT (phones outside of NAT work correctly and correlate = nat=no configured in Asterisk or a SIP ALG in use)
- Extensions/Endpoints configured with NAT=yes in asterisk
- No SIP ALG at the firewall with the NAT enabled endpoints/extensions. 

I have the PCAP I can provide if there is a private way to provide it. 

Not sure what else to do.

**Comment by TheZLabs** [comment]
Having the same issue with Genesys media servers. SIP data makes it fine. RTCP Fail count just continues to go up. Running debug indicates NocorrelationID, same as above. Would really love to get QoS data from Homer for all these calls. Not much point for me to use it if this part doesn't work. Everything else seems to work really well with this exception. I did the docker setup if it matters.

**Comment by Demolish50** [comment]
> Having the same issue with Genesys media servers. SIP data makes it fine. RTCP Fail count just continues to go up. Running debug indicates NocorrelationID, same as above. Would really love to get QoS data from Homer for all these calls. Not much point for me to use it if this part doesn't work. Everything else seems to work really well with this exception. I did the docker setup if it matters.

I'm able to get a lot more correlation with captagent, but not perfect. I get all the RTP streams from the PBX to the phones correlated but none from the PBX to the SIP provider.  Trying to see what to do about that now.

**Comment by lmangani** [comment]
To address this type of scenario, focus on the SDP portion of the calls missing the SIP/RTCP correlation. The answer is most likely NATting,

**Comment by Demolish50** [comment]
Thanks for the reply. It certainly is a NAT issue, I'm 99% sure. I'm not not sure how captagent manages to figure it out. 

I did manage to get captagent to sort out both sides. PBX to SIP provider and PBX to endpoints in this configuration, but I have another issue with captagent with RTCPXR and would rather use heplify client anyway. 

I can't seem to get heplify client to do the same. I can get heplify to now correlate correctly from PBX to SIP trunk provider (no natting) but I am unable to get it to correlate from PBX to phones when the phones are behind NAT. Its obvious why, SDP shows an internal address and the RTP address is different. 

What exactly would you like pasted? I'm trying to figure out how captagent does this coloration so I can offer a suggestion.

**Comment by lmangani** [comment]
HEPlify should do the [same](https://github.com/sipcapture/heplify/blob/master/decoder/correlator.go#L34) thing `nat-enable` in captagent does, so having some examples would help locate the potential issue.

**Comment by Demolish50** [comment]
I can send you the capture I just did. Do you have a private way I can provide it?

I can see in the capture that the message body of the SDP contains "Connection Information (c): IN IP4 192.168.1.135"

While at the same time I see this in the debug output. 

2020/08/20 21:52:55.388655 correlator.go:147: DBG [rtcp] No correlationID for srcIP=34.203.251.161, srcPort=19559, dstIP=**redactedpublicIP,** dstPort=16621, payload={"sender_information":{"ntp_timestamp_sec":3806949174,"ntp_timestamp_usec":3232310656,"rtp_timestamp":2763387128,"packets":29247,"octets":4679520},"ssrc":2035215409,"type":202,"report_count":1,"report_blocks":[{"source_ssrc":64651983,"fraction_lost":0,"packets_lost":10,"highest_seq_no":38173,"ia_jitter":23,"lsr":1865531259,"dlsr":327680}],"report_blocks_xr":{"type":0,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_duration":0,"round_trip_delay":0,"end_system_delay":0},"sdes_ssrc":2035215409}

**Comment by Demolish50** [comment]
I guess this should probably go somewhere else and we can close this issue but I'll go ahead and share what else is going on. 

I still can't get RTCP-XR to show up in homer. Heplify is delivering the XR data to the server that homer/loki/Prometheus is on. XR data shows up in loki and in Prometheus but in homer on the QoS tab it does not. I see the non XR packets from the pbx to the phone but the XR packets from the phone to the PBX just aren't there even though the data is there in loki and prom.

**Comment by Demolish50** [comment]
I've verified that the data actually exists in the homer_data DB, in both directions. 

Just one is missing from the QoS tab, no idea why but I guess that's a homer thing so I'll close this.
