### ISSUE TITLE
heplify client for windows

### ISSUE THREAD

**Issue by shchbo** [sipcapture/heplify#199]
is there a heplify client for windows?
in this https://github.com/sipcapture/heplify there is a redirection for heplify.exe file for windows but it leads to the linux files

**Comment by negbie** [comment]
Under Version 1.47 is a binary which was compiled for windows. If you want a more recent version just compile it. To do so install Go runtime and npcap.

**Comment by shchbo** [comment]
if i use the 1.47 version how do i use it?

**Comment by negbie** [comment]
https://github.com/sipcapture/heplify#examples
