### ISSUE TITLE
heplify is stopping to send data

### ISSUE THREAD

**Issue by magacho** [sipcapture/heplify#203]
Hi Everyone, I'm trying to use Homer as a monitoring system for IVR but it suddenly stops to grab the hep data. and is apears again without a reason. 
The only error I got is this: 
`2021/01/30 15:03:42.242924 loki.go:134: ERR send size batch: server returned HTTP status 400 Bad Request (400): entry with timestamp 2021-01-30 15:03:42.057901842 +0000 UTC ignored, reason: 'entry out of order' for stream: {job="heplify-server", node="1234", type="rtcp"},`
an than it tooks a day and starts back again.
Did anyone knows how to find the reason for that?
Thanks.

**Comment by lmangani** [comment]
The error appears to be related to Loki returning errors. Have you tried disabling the Loki output as a starter? A vanilla setup would not need/benefit from it much.
