### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by shchbo** [sipcapture/heplify#206]
when i try running heplify client on my linux machine i get "Segmentation fault" error.
how can i resolve this issue?

**Comment by negbie** [comment]
> how can i resolve this issue?
Well one way would be to analyze the problem, fix the problem and send a pr or by providing more infos.

**Comment by shchbo** [comment]
how can i analyze this issue and what info do you need in order to help me?

**Comment by shchbo** [comment]
i tried using the 1.62 version and it is working.

**Comment by negbie** [comment]
Perfect, problem solved ;)
