### ISSUE TITLE
heplify sevice stopped randomly and didn't see any error logs

### ISSUE THREAD

**Issue by rvanza** [sipcapture/heplify#213]
Hello,

I am using below mention command to start heplify service and logs write into /home/heplify.log file. The heplify service randomly stopped working and didn't see logs in helplify.log file.

Can you please help me out to resolve this issue?
 
./heplify -l error -i ens192 -pr 9000-9001 -hs Hepic_server_Ipaddres:9062 -dim OPTIONS -nt tcp &

Thank you.

**Comment by lmangani** [comment]
I'm afraid we can't troubleshoot much about random events w/o any specific indicators - might be your system killing the process for memory constraints or anything else unrelated. If you are sure the system is not involved, you might want to enable debug mode and perhaps run heplify as a service and see if the systemctl logs or patterns suggest anything.

**Comment by rvanza** [comment]
Hi lmangani, Thank you for the quick reply.
 
Can you please guide me for this?

1. how to set heplify as a service.
2. how to enable debug mode.
3. how to enable logs.

Thank you.

**Comment by lmangani** [comment]
Sure:

- [service example](https://github.com/sipcapture/heplify/blob/master/example/heplify.service)
- [parameters](https://github.com/sipcapture/heplify#usage)

It seems you already have logging set to `error` so its the same approach but with syslog
