### ISSUE TITLE
The mode name SIPRTP

### ISSUE THREAD

**Issue by Gomam0n** [sipcapture/heplify#214]
Can we enter SIPRTP as the mode argument(-m)? What is the difference between SIPRTP and SIPRTCP?

**Comment by negbie** [comment]
Yes, the purpose of SIPRTP is to capture SIP+RTP+RTCP while SIPRTCP should skip RTP. SIPRTP makes only sense if you use heplify with the -wf flag and you want a dump with  SIP+RTP+RTCP.
