### ISSUE TITLE
heplify can capture the packet it sends

### ISSUE THREAD

**Issue by Gomam0n** [sipcapture/heplify#215]
I have noticed that heplify can capture the packet it sent (HEP3 packet) and encode it and sent another packet. So the packet size will be larger and larger. I know it can be prevented by set a small portrange (not including the port that heplify uses). But is there any other method to prevent this?

**Comment by negbie** [comment]
Currently not, sorry. Just use different ports for in and out.

**Comment by lmangani** [comment]
@Gomam0n captagent can easily do this, but at the cost of not being as portable as heplify
