### ISSUE TITLE
heplify 1.63/go1.16.5 on armv7l causes panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by rpn0709** [sipcapture/heplify#216]
panic: unaligned 64-bit atomic operation

goroutine 13 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x6d2639c, 0x0, 0x450cd8)
        /usr/local/go/src/runtime/internal/atomic/asm_arm.s:263 +0x14
github.com/sipcapture/heplify/decoder.(*Decoder).printPacketStats(0x6d26000)
        /root/heplify-1.63/decoder/util.go:101 +0x2c
github.com/sipcapture/heplify/decoder.(*Decoder).printStats(0x6d26000, 0xf8475800, 0xd)
        /root/heplify-1.63/decoder/util.go:129 +0x5c
created by github.com/sipcapture/heplify/decoder.NewDecoder
        /root/heplify-1.63/decoder/decoder.go:145 +0x5a4

**Comment by tcreek** [comment]
I am getting something similar, but I compiled the source with Go version 1.18.4

**Comment by cmsmith1977** [comment]
I found a similar issue in another project (https://github.com/hashicorp/consul/pull/10515) , and was able to move the _ entry in this struct to the end to fix this

diff --git a/decoder/decoder.go b/decoder/decoder.go
index f6ff9d9..2affade 100644
--- a/decoder/decoder.go
+++ b/decoder/decoder.go
@@ -50,7 +50,6 @@ type Decoder struct {
 }

 type stats struct {
-       _             uint32
        fragCount     uint64
        dupCount      uint64
        dnsCount      uint64
@@ -63,6 +62,7 @@ type stats struct {
        sctpCount     uint64
        udpCount      uint64
        unknownCount  uint64
+       _             uint32
 }
