### ISSUE TITLE
Heplify is not running on Windows

### ISSUE THREAD

**Issue by ajith339** [sipcapture/heplify#217]
Hi Everyone,
I am a newbie and trying to run Heplify on my Windows lab and downloaded version 1.47 which is the latest exe available for download. Upon trying to install, just a screen flash happens and nothing else.
Is there a latest version available or is there something else I should do to get it up and running?

Please help.

Thanks in advance.

**Comment by lmangani** [comment]
Sorry we couldn't help. Closing
