### ISSUE TITLE
Centos6 cannot be installed

### ISSUE THREAD

**Issue by 15279845180** [sipcapture/heplify#225]
Centos6 cannot be installed

**Comment by lmangani** [comment]
how so? which method did you follow? provide some indications or we won't be able to help at all

**Comment by 15279845180** [comment]
My Softswitch doesn't support hep, so I'm trying various clients

**Comment by lmangani** [comment]
The following should work and if it doesn't you need to paste the full error and/or core dump
```
wget https://github.com/sipcapture/heplify/releases/download/1.63/heplify
chmod +x heplify
./heplify
```

**Comment by 15279845180** [comment]
I always thought I needed to compile with go at the terminal. I'll try this you sent. Thank you

**Comment by lmangani** [comment]
No, You don't need to do so if the release binary works. If it doesn't you might need it.
