### ISSUE TITLE
Trying MIPS Build

### ISSUE THREAD

**Issue by hhsfool** [sipcapture/heplify#23]
Hello, I've got all the dependencies downloaded and successfully built from source on linux amd64 architecture.  I'm trying to build a MIPS64 version of heplify but I'm getting this error: "sniffer/afpacket_linux.go:18:11: undefined: afpacket.TPacket"
I've looked at the go file and can't find any reasons why this is happening.  Is there something you can think of? Or am I way off base trying to build a MIPS64 version?  FYI I'm wanting this for our Unifi USG devices that run on a modified Debian 8 MIPS64 version.

Thanks for any help or response!

**Comment by negbie** [comment]
Hi, never tried to build it for MIPS64. Will have a look into it over the day.

**Comment by negbie** [comment]
I was able to compile it but I have nothing to test it ;) Please test heplify-linux-mips64 from releases. If you want to build it yourself here is how I did it:

1) You need docker
2) go get github.com/ykyuen/xgo
3) create the folder xgo-dist and move the xgo binary there
4) run:
xgo --deps=http://www.tcpdump.org/release/libpcap-1.8.1.tar.gz --depsargs=--with-pcap=linux --targets=linux/mips64 github.com/negbie/heplify

**Comment by negbie** [comment]
Keep in mind that you need about 60-80 mb free ram

**Comment by hhsfool** [comment]
This works beautifully!  Thanks so much for compiling this for me.  I didn't do it with docker, so I'll get that setup going so I can keep up with your releases. Appreciate it very much!

**Comment by tcreek** [comment]
I was able to compile using this method, but after trying the three different targets, and trying on two different brand routers, they all failed with errors, or returning "Illegal Instruction."

Any advice for debugging? I am not seeing debug options for xgo like one can see for GNU C/C++ compilers.

I am asking because you seem to have expert experience with GOlang and this xgo.

Thanks

**Comment by negbie** [comment]
Hi @tcreek 
make sure your routers are really mips64 and not

mips, mipsle (32-bit MIPS big- and little-endian)
mips64le (64-bit MIPS big- and little-endian)

**Comment by tcreek** [comment]
So are you saying the routers must be 64 bit MIPS, and the 32 bit targets of mips, and mipsle will not work out? If so, would that be because of the libpcap-1.8.1 being compiled in 64 bit?

Thanks!

**Comment by tcreek** [comment]
That is what I am saying, I tried all three targets (mips64, mips, and mipsle) on two different routers and they all failed. That I why I am asking about debugging help. and asking if libpcap is the cause of not functioning on 32 bit MIPS processors.

**Comment by negbie** [comment]
Ah ok I thought you've just tested it with three devices without adjusting the build parameter. Well you could use following build flags for xgo to get some more details:
-v: prints the names of packages as they are compiled
-x: prints the build commands as compilation progresses

More here:
https://github.com/karalabe/xgo

Another way:
download ibpcap-1.8.1.tar.gz

Build libpcap
    export CC=mips-linux-gnu-gcc
    ./configure --host=mips-linux-gnu --with-pcap=linux > /dev/null
    make CFLAGS='-w' -j4 > /dev/null


env CC=mips-linux-gnu-gcc CGO_ENABLED=1 GOOS=linux GOARCH=mips CGO_LDFLAGS="-L/tmp/libpcap-1.8.1/ " go build -o heplify

you need make,yacc,flex,mips-linux-gnu-gcc

**Comment by tcreek** [comment]
I should be able to do something with that.

Thanks a lot!
