### ISSUE TITLE
Heplify stops writing PCAPs

### ISSUE THREAD

**Issue by haeferer** [sipcapture/heplify#234]
Hi,

First of all Heplify is cool software and was very easy to integrate. Currently we run into some problems

We are using heplify to (at first) write Pcap-Files. This works fine, but Heplify always stops after a defined number of hours / packages ?! During our tests it ends after 12hours (~ 12 pcaps files).

It looks like a feature ? (Maximal number of pcap files / pcap data written)

Thanx for any help or hint about this

Greetings

Andreas

**Comment by lmangani** [comment]
Thanks for the kind words credit goes to @negbie 
This use case is not part of our support scope as you are clearly not using any collector. There are better applications for writing pcaps to disk while our is intended for streaming it back to a HEP collector primarily. I'd suggest checking out stenographer, n2disk or something made for the purpose.

**Comment by haeferer** [comment]
No Problem. 

Thx for your fast support !
