### ISSUE TITLE
-m SIP does not exclude RTCP

### ISSUE THREAD

**Issue by chapmanw** [sipcapture/heplify#243]
Hi

With the -m flag set to SIP RTCP is still being collected. 

With this applied the logs show the mode set: 
Logging:(*logp.Logging)(0xc00009e0f0), Mode:"SIP"

But the traffic being saved still included both SIP and RTCP.

Thanks

**Comment by lmangani** [comment]
Thanks for the report. Kindly attach some evidence of this behaviour? ie: any RTCP packets sent via HEP using this mode.

**Comment by chapmanw** [comment]
Well... it's looks like there was an old Heplify instance still running that was sending the RTCP traffic. Sorry for wasting your time!

**Comment by lmangani** [comment]
No problem!
