### ISSUE TITLE
HEP Collector - network unavailable scenario 

### ISSUE THREAD

**Issue by idanacontaqt** [sipcapture/heplify#250]
hey,

my capture architecture is as follow:

- Sip traffic goes to a native freeswitch agent thats sends hep to a localhost heplify in hep collector configuration.

- the hep collector sends hep in tls to remote heplify-server.

my question is what happens when there is a network disconnect between the hep collector to the captue-server in this configuration?

i saw there are default configurations for: 

- buffer(  -b in	Interface buffersize (MB) (default 32)) 
- retry attempts( -tcpsendretries uint Number of retries for sending before giving up and reconnecting (default 64))  

are these settings relevant to this scenario ?

P.S. - I know i ask quite a few questions here lately and i want to thank you for your professional, helpful and quick replies to my "newb" questions. :)

**Comment by idanacontaqt** [comment]
thanks for the fast replay!

So you suggest use HPF instead of heplify as HEP collector? Does HPF supports tls connection to HEP capture server?

**Comment by lmangani** [comment]
No, HFP does not replace heplify. It's a buffering proxy you need to deploy in front of your HEP agents.

**Comment by kYroL01** [comment]
@idanacontaqt it should be 
**Native Freeswitch agent -> heplify(Hep Collector) -> HFP -> remote HEP server**

**Comment by kYroL01** [comment]
@idanacontaqt the diagram here will help you https://github.com/ivlovric/HFP#flow-diagrams

**Comment by idanam-del** [comment]
I see thank you
