### ISSUE TITLE
Heplify installed on 3cx vm

### ISSUE THREAD

**Issue by francesco-amato-argo** [sipcapture/heplify#252]
Hi to all
I'm trying to collect SIP traffic from a 3cx vm
I have setup the heplify-server and the heplify agent on different vms
When I run the heplify agent, I saw the traffic captured by th eagent but I can't see any packet transfer to the vm with heplify-server
There is someone that can help me?

**Comment by lmangani** [comment]
if you see `heplify` sending traffic on 9060 and nothing arrives on the other side, you have a firewall issue.

**Comment by francesco-amato-argo** [comment]
You are right
The problem was the provider firewall

Thank you for your help
