### ISSUE TITLE
latest Binary will not run on windows 10

### ISSUE THREAD

**Issue by natek777** [sipcapture/heplify#27]
I get a message using the latest binary saying that this program is not supported in windows 10 x64

This is after adding the .exe extension

Several versions prior does seem to work.

Thanks,
Nate

**Comment by negbie** [comment]
Hi Nate,
you cannot simply rename the binaries to make them work on different platforms. The only version I built for Windows x64 was Version 0.85. If you want I can build a windows version for 0.98 tommorw.

**Comment by natek777** [comment]
That would be great! I wondered why it did not have an extension....

Also the "any" nic option does not appear to work in windows, is that fixed in .98?

Do know of any way to script the NIC detection otherwise?

Thanks!

**Comment by negbie** [comment]
Will see if I can find some time this evening. As far as I know there is no any Interface for windows. So simply spawn one heplify process per interface. heplify for windows is a goodie and not my main focus because I don't even have one single machine with windows :)

**Comment by negbie** [comment]
Build latest version for windows and uploaded it to releases.
