### ISSUE TITLE
Can’t get -dim to work on multiple methods

### ISSUE THREAD

**Issue by ajb142** [sipcapture/heplify#278]
Looking for some clarification on the `-dim` option. 

I would like to pass “OPTIONS,NOTIFY,REGISTER” but can only seem to make one work, no combination of the three. 

Should it be possible to filter out more than one? 

Is this syntax correct on the command line `-dim “OPTIONS,NOTIFY,REGISTER “` ? 

I can see that these sip methods are still sent to the hep server when more than one method is specified. 

Thanks in advance

**Comment by lmangani** [comment]
The documented example syntax is not using any quotes and no extra whitespace should be included. Are you using Docker?
```
./heplify -dim OPTIONS,NOTIFY
```

The devil is often in the details. Please include your actual configuration and if the issue persists we'll try to replicate it.

**Comment by ajb142** [comment]
Thanks for the clarity.

I will give this a go later / tomorrow, was not expecting such a fast response!!

**Comment by ajb142** [comment]
Thanks for the suggestion but no luck. 

I copied the example, changed the target ip address and I can still see OPTIONS and NOTIFIES being sent to the HEP server. 

what `-dim` does seem to be doing successfully if filtering out status messages where the cseq contains the relevant method. It is not filtering the original request despite the cseq header in there also containing the correct method.

**Comment by lmangani** [comment]
`dim` filters traffic exclusively by CSE as you can also confirm from [the source](https://github.com/sipcapture/heplify/blob/8c1057a6eaf8654816ced1432ca3aba36e2334dd/decoder/decoder.go#L247)

Details matter. Please attach the actual config + examples for the unfiltered messages or we won't be able to reproduce and assist.

**Comment by lmangani** [comment]
@ajb142 I do not exclude this being a bug but without some examples it's hard to tell. BTW If you want to show an example for a message that's not fltered, you can and should anonymize any message details, they are not important.
