### ISSUE TITLE
[QA]build on windows

### ISSUE THREAD

**Issue by pedoc** [sipcapture/heplify#281]
Hi guys
First of all thank you for making such a great tool

Currently I hope to be able to compile ``heplify`` under windows. I looked up historical issues and conducted a google search and found that currently only version ``1.4.7`` has a windows release version, and the latest version is already ``1.6.x``

At the same time, I didn't see any instructions or instructions for compiling on windows.
I tried running go build in windows and it prompted me
```
github.com/sipcapture/golua/lua: build constraints exclude all Go files in C:\Users\Administrator\go\pkg\mod\github.com\sipcapture\golua@v0.0.0-20200610090950-538d24098d76\lua
```

I also tried installing golang in ``msys2`` and running the compile command:
```
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build
```
This will output the following error message:
```
# runtime/cgo
gcc_libinit_windows.c: In function ‘_cgo_beginthread’:
gcc_libinit_windows.c:143:27: error: implicit declaration of function ‘_beginthread’; did you mean ‘_cgo_beginthread’? [-Werror=implicit-function-declaration]
   143 | thandle = _beginthread(func, 0, arg);
       | ^~~~~~~~~~~~
       | _cgo_beginthread
cc1: all warnings being treated as errors
```

As of now, I can't compile it successfully under windows, any help would be greatly appreciated

environment:
go version:1.21.0
window os version: windows 11 workstation pro
msys64 go version:1.22.1 
msys64 gcc version:13.2.0

**Comment by pedoc** [comment]
I solved this problem
Using ``mingw64`` environment in ``msys2``
and run
```
git clone https://github.com/sipcapture/heplify.git
pacman -S mingw-w64-x86_64-go
```

After go installation, modify ``~/.bashrc`` and set environment variables
```
export PATH=/mingw64/lib/go/bin:$PATH
export GOROOT=/mingw64/lib/go
export GOPATH=/mingw64
```
and run 
```
pacman -S mingw-w64-x86_64-gcc
pacman -S mingw-w64-x86_64-luajit
```
and run
```
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build -ldflags "-s -w"
```

copy ``lua51.dll`` to ``heplify.exe`` directory,done

![image](https://github.com/sipcapture/heplify/assets/6604230/e7a56738-8235-4e8b-b434-cc004e35a1a4)

**Comment by pedoc** [comment]
Unfortunately, successful compilation does not mean that it can run correctly.

![image](https://github.com/sipcapture/heplify/assets/6604230/0747ccf9-1ef5-4240-91e3-0f3674ce0563)

It seems that there is no compatibility support for window in the code

**Comment by pedoc** [comment]
ok, I overlooked it, on windows you should specify -t pcap

**Comment by kYroL01** [comment]
Thank you very much @pedoc
