### ISSUE TITLE
Heplify Windows 64bit Version

### ISSUE THREAD

**Issue by system2477** [sipcapture/heplify#287]
Hi,

I'm looking to download Heplify and run this on a windows machine (64bit) however when I run the application, I get the error message, "this app can't run on your PC". I have experimented with different compatibility modes however it's still the same result. I'm running this on Windows 10 Pro x64.

Is Windows 64 bit version of Heplify available/supported? if not could this be complied and posted please? Thanks.

**Comment by system2477** [comment]
Compiled and now working.

**Comment by kYroL01** [comment]
Thank you @system2477 for the feedback
