### ISSUE TITLE
Sizing

### ISSUE THREAD

**Issue by abitrusty** [sipcapture/heplify#294]
Hi - don't have an issue but is there any information on agent sizing.

Can an Heplify agent running on a Linux server with 1 x vCPU and 4GB handle 100Mb of concurrent Voip traffic easily?

Any info appreciated?

**Comment by lmangani** [comment]
When talking about "vCPU" and without any real details this type of question is impossible to answer. The real issue is usually the network and not the agent. Try it out and let us know if you experience issues.

**Comment by abitrusty** [comment]
hi thanks for reply. I don't have any specifics as haven't deployed anything yet but am wondering what (if any) capacity issues i might hit. Each heplify agent might be receiving over 100Mbps  of sustained spanned SIP/RTP traffic. Are there any considerations I need to make in regards to the underlying linux VM to support this amount of traffic

**Comment by lmangani** [comment]
With 100Mbps of traffic you should see no issues. If the processing will max out the CPU you will simply need to scale up as It all depends on the complexity of the underlying traffic being captured, reassembled, dissected, extracted, correlated, etc. Each VM setup is different - some do great, some do not. Always watch for [kernel drops](https://www.cyberciti.biz/faq/linux-show-dropped-packets-per-interface-command/) and prefer TCP delivery for HEP packets.
