### ISSUE TITLE
Quick heplify agent question

### ISSUE THREAD

**Issue by abitrusty** [sipcapture/heplify#299]
I'm going to capture voip traffic using heplify client via erspan and send to heplify server and don't want loads of extra traffic traversing the network. Will the heplify client send all the captured RTP traffic to the heplify server or does it jsut parse the SIP and RTCP traffic and send it.

In other words do I need to just put the heplify client close to the voice source or do I need to put the heplify server with it?

Sorry not an issue but can't find where I should post a question like this

**Comment by kYroL01** [comment]
Hi @abitrusty 
heplify only deal with SIp and RTCP, not with the real media (RTP).

To work with RTP you need a different agent (_rtpagent_) that makes the RTP analysis, but this is a paid product.
If you need more information about it, please contact [](https://hepic.tel/contact/)

Thank you
