### ISSUE TITLE
Is Windows heplify.exe still available?

### ISSUE THREAD

**Issue by Wolffis** [sipcapture/heplify#307]
The latest Windows build heplify.exe is from 2018 version 1.47. I tried to build one myself but only got errors:

> go version
go version go1.23.2 windows/amd64

> go build -o heplify.exe main.go
github.com/sipcapture/golua/lua: build constraints exclude all Go files in C:\Users\xxx\go\pkg\mod\github.com\sipcapture\golua@v0.0.0-20200610090950-538d24098d76\lua

I don't know much about Go and could not find any solution, therefore is Windows still even supported?

**Comment by lmangani** [comment]
Hello @Wolffis 

Windows is supported as a build platform but not as distribution target - the build process is up to you.
You can compile a windows version by using a compatible GO runtime and npcap library. If you have errors, share them.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify/releases/download/2.0.19/heplify_windows_amd64.exe
