### ISSUE TITLE
Some problems in use

### ISSUE THREAD

**Issue by Interesting993** [sipcapture/heplify#311]
this is my docker compose file：

![image](https://github.com/user-attachments/assets/a97d3c93-7dd1-4a29-9071-788e217aa898)

1、my homer web  received some confusing stuff
![image](https://github.com/user-attachments/assets/abff954f-5aef-46b5-abe0-19ee7008e502)

why my SIP Method displayed this。Normally there is only a status code here、How can I confirm why this happens

2、i use -wf parameter。But there is only a directory, and there is no pcap package file in the directory.
log file：
2024-11-07T13:01:07Z INFO opening new pcap file any_interface.pcap.tmp.gz

**Comment by lmangani** [comment]
It's hard to tell without knowing anything about the packets. I would suggest using only basic parameters in heplify as a starting point following the default examples. You really shouldn't use the -wf parameter as it has nothing to do with HOMER and its not required for usage.

**Comment by Interesting993** [comment]
I use the -wf parameter to verify another scenario. Can the packets captured by heplify carry media streams?   I also use pcapsipdump to capture the complete call packet, but I recently found that it has many problems. Is there any similar one that you can recommend to me?

**Comment by lmangani** [comment]
> Can the packets captured by heplify carry media streams?

I'm afraid we cannot help, media recording is not a feature by design and for RTP/RTCP our agents only emit statistics. 
We are generally against audio interceptions and our tools and agents do not facilitate that outside the bare minimum.
