### ISSUE TITLE
heplify386 v1.0 compiled doesn't run

### ISSUE THREAD

**Issue by gjocys** [sipcapture/heplify#32]
Debian 7, i686

```
root@localhost:/opt/heplify# /opt/heplify/heplify386 -hs 127.0.0.1:9060

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb74ec87c]

goroutine 1 [running]:
sync/atomic.AddUint64(0x97636cb4, 0x1, 0x0, 0x1, 0x79eb3042)
	/usr/lib/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/coocood/freecache.(*segment).get(0x97636c88, 0x9bfd802a, 0x22e, 0x22e, 0x3042c69e, 0x65250c3f, 0x87234088, 0x0, 0xb7955b80, 0x9bfce000, ...)
	/go/src/github.com/coocood/freecache/segment.go:201 +0x44a
github.com/coocood/freecache.(*Cache).Get(0x9760a000, 0x9bfd802a, 0x22e, 0x22e, 0x0, 0x97484188, 0x4, 0x9bfca000, 0x0)
	/go/src/github.com/coocood/freecache/cache.go:56 +0xaa
github.com/negbie/heplify/decoder.(*Decoder).Process(0x97482280, 0x9bfd8000, 0x258, 0x258, 0x97480720, 0x258, 0x258, 0x258)
	/go/src/github.com/negbie/heplify/decoder/decoder.go:108 +0x1e56
github.com/negbie/heplify/sniffer.(*MainWorker).OnPacket(0x97658008, 0x9bfd8000, 0x258, 0x258, 0x97480720)
	/go/src/github.com/negbie/heplify/sniffer/sniffer.go:74 +0x49
github.com/negbie/heplify/sniffer.(*SnifferSetup).Run(0x9754c050, 0xb7839208, 0x9754c050)
	/go/src/github.com/negbie/heplify/sniffer/sniffer.go:287 +0x32a
main.main()
	/go/src/github.com/negbie/heplify/main.go:88 +0xe6
```

**Comment by negbie** [comment]
Hi, this is due to the latest changes in freecache. I opened a issue there
https://github.com/coocood/freecache/issues/36

Mby I will replace it with another cache lib.

**Comment by negbie** [comment]
I updated the 386 binary from releases with my changes I made to freecache. Could you please test it again?

**Comment by gjocys** [comment]
Hi negbie,

Thanks for your prompt help here!

Are you sure you updated releases? File size is exactly the same. Error as well.

**Comment by negbie** [comment]
Yes I am sure. I did not add or remove anything just reordered stuff, thats why its the same size.
Sadly this means my changes were not enough to fix this. What you can do right now is to run heplify with following flags.

-dd=false -m SIP

This means heplify won't deduplicate messages (therefore I use freecache) and you only get SIP, no RTCP (therefore I use freecache too)

**Comment by negbie** [comment]
Any way is it the exact same error message? Could you paste it here?

**Comment by gjocys** [comment]
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb74c087c]

goroutine 1 [running]:
sync/atomic.AddUint64(0x9762e304, 0x1, 0x0, 0x1, 0x2ed6c695)
	/usr/lib/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/negbie/freecache.(*segment).get(0x9762e2f4, 0x9bfa46ea, 0x1e2, 0x1e2, 0xc695c8a3, 0x9cf537d4, 0x872084d8, 0x0, 0xb7929b80, 0x31000000, ...)
	/go/src/github.com/negbie/freecache/segment.go:201 +0x44e
github.com/negbie/freecache.(*Cache).Get(0x97600000, 0x9bfa46ea, 0x1e2, 0x1e2, 0xb, 0x20, 0x1, 0x1, 0x0)
	/go/src/github.com/negbie/freecache/cache.go:56 +0xaa
github.com/negbie/heplify/decoder.(*Decoder).Process(0x974b8200, 0x9bfa46c0, 0x20c, 0x20c, 0x974baae0, 0x20c, 0x20c, 0x20c)
	/go/src/github.com/negbie/heplify/decoder/decoder.go:108 +0x1e56
github.com/negbie/heplify/sniffer.(*MainWorker).OnPacket(0x974b60f0, 0x9bfa46c0, 0x20c, 0x20c, 0x974baae0)
	/go/src/github.com/negbie/heplify/sniffer/sniffer.go:74 +0x49
github.com/negbie/heplify/sniffer.(*SnifferSetup).Run(0x974d20a0, 0xb780d1e8, 0x974d20a0)
	/go/src/github.com/negbie/heplify/sniffer/sniffer.go:287 +0x32a
main.main()
	/go/src/github.com/negbie/heplify/main.go:88 +0xe6`

**Comment by negbie** [comment]
Next build online. Let's hope this could fix this:
https://github.com/negbie/freecache/commit/4cd2b55371eeffa37b3b51f77f36dc27102b57d5

Could you try it again please?

**Comment by negbie** [comment]
Ok my pull request has been merged. https://github.com/coocood/freecache/pull/38
So we should be able to use it on i386 again. Will drop my fork and use coocood/freecache again.

**Comment by negbie** [comment]
@gjocys do you still need help?

**Comment by gjocys** [comment]
Thanks for your help @negbie! Seems to be working fine now.
