### ISSUE TITLE
RTCP-XR Not being reflected in Homer.

### ISSUE THREAD

**Issue by 00Asgaroth00** [sipcapture/heplify#44]
Hi,

The readme for heplify says "Heplify is able to send SIP, correlated RTCP, RTCPXR, DNS, Logs into homer.", I'm wondering how it goes about doing this, I'm guessing while sniffing it "detects" an RTCP-XR PUBLISH from a UA and does its thing and sends the stats over to homer/kamailio, homer/heplify-server.

If my understanding above is correct, then, I think I've may have come across an RTCP-XR PUBLISH message that heplify is not handling. What I mean is, I can see the publish in homer's data/web-ui, but when I look at the call that the rtcp-xr publish is associated with, then, I don't see any rtcp-xr stats on the QoS reports tab of the call.

I have a pcap of the publish, but it contains some sensitive info, so I cannot upload it to github.

Any thoughts?

**Comment by negbie** [comment]
Please take a look here
https://tools.ietf.org/html/rfc3611
under point 2. A subset of this rtcp-xr report will be caprured by heplify.

Heplify doesn't look inside SIP publish. If I remember it right I wrote some time ago a kamailio config which does this. Will add it in the near future when homer7 beta lands on github for heplify-server.

**Comment by 00Asgaroth00** [comment]
Ahh I see, so you're only looking at the rtp control packets and if it is an extended report you're grabbing it. I misinterpreted the readme.

I recall seeing something about RTCP-XR publish messages being processed in kamailio in the wiki too some time ago. Problem is, I really, really... really like heplify-* thus far. Guess I'll be waiting for H7-beta so to see this.

Thanks for reading :)

**Comment by negbie** [comment]
Exactly. I want to avoid the need to look into SIP as much as possible on the client side. This changes on the Server side where I need to parse SIP anyway.

**Comment by 00Asgaroth00** [comment]
Thanks, shall I open a ticket on heplify-server repo as a reminder? Then we can close this one.

**Comment by negbie** [comment]
Sure go ahead.
