### ISSUE TITLE
Disregarding uninteresting packets (-di) eg: OPTIONS

### ISSUE THREAD

**Issue by 00Asgaroth00** [sipcapture/heplify#45]
Hi,

How does the "disregard uninteresting" option work. Does it disregard based on the sip method (and associated replies) or is it essentially an exclusion of a particular sip method if some of its headers/header-content match the string given to "-di"?

As an example, if I want to exclude all OPTIONS messages and associated responses, then I try to run as follows:
```
heplify -pr 5060 -hs homer_ip:port -di " OPTIONS"
```
The above example has a space preceding the word OPTIONS, I've also tried it without pre/post spaces.

When I run the above command, options messages are excluded, but, I've noticed, that some messages that contain the word options in it are also excluded. An example, an initial INVITE message that has an "Allows:" header that contains the word OPTIONS. Using spaces to try and overcome the exclusion of the INVITE only results in other UA's initial invite being excluded.

If "-di" is indeed a "grep" style match across a message to be excluded, would it be possible to have an additional option that would exclude a sip method and associated responses. So instead of checking headers/bodies for a string match, check the sip method (INVITE/REGISTER/OPTIONS etc) and exclude it based on the sip method? By exclude I mean to exclude the message and associated responses.

If we could have an option to exclude on sip method, would it be possible to allow multiple exclusions, as an example(s), if the new arg option was "-dim":
```
heplify -pr 5060 -hs homer_ip:port -dim "OPTIONS"
heplify -pr 5060 -hs homer_ip:port -dim "OPTIONS|SUBSCRIBE"
heplify -pr 5060 -hs homer_ip:port -dim "OPTIONS|SUBSCRIBE|PUBLISH"
```

Thanks for reading :)

**Comment by negbie** [comment]
Yip, -fi and -di are like grep so you need to be carefull for SIP because of the allow header or other shitty SIP stuff (and you will find alot of shit in SIP) 

What you want is easy to do and I will implement it when I am back in germany.

**Comment by 00Asgaroth00** [comment]
Excellent, thanks, l give it a test whirl once you've had a gap to implement it.

**Comment by negbie** [comment]
Hi, 
when you compile latest source you should have a new flag -dim
With that you are able to drop comma separated SIP methods (-dim "OPTIONS,NOTIFY")

**Comment by 00Asgaroth00** [comment]
Thanks, I will give this a test over the coming day or two. I'll get back to you with results.

**Comment by negbie** [comment]
Version 1.2 under releases can be used now

**Comment by negbie** [comment]
Closing here because of no response.

**Comment by 00Asgaroth00** [comment]
Oh, sorry, I totally forgot about this one, the additional parameter is working beautifully, thank you!
