### ISSUE TITLE
Missing HEP packet (estimate occur 1 or 2 times in a hour)

### ISSUE THREAD

**Issue by games130** [sipcapture/heplify#49]
I am using the latest heplify (self compile)

tcpdump done on server interface:
- p1p2 (port mirror done on LAN Switch)
- lo (loopback heplify and heplify-server on the same machine)

I am able to see the INVITE message from tcpdump capture on p1p2 but it was not encapsulated in HEP(seen from lo interface tcpdump).

I have tried to run heplify and select the pcap file to insert the SIP messages, it is working.
So this means there is no problem with the encapsulation of the SIP into HEP.
Probably something went wrong during the running of heplify.

The problem does not happen everytime (So far based on sample check most of the time it is working fine), i estimate mabye 1 or 2 packet are not encapsulated in 1 hour (I am only checking INVITE so cant say for sure if other messages are affected due to too many calls to manually check).

Any suggestion on how I can troubleshoot this?

**Comment by games130** [comment]
![tmp](https://user-images.githubusercontent.com/32865575/39982330-966904f2-5786-11e8-8fe4-9d639d6cfbb2.png)

**Comment by negbie** [comment]
What commandline flags are you using? Are those packets > 8192 bytes? You can try to turn off deduplication with -dd=false

Depending on traffic load you better use af_packet with -t af_packet (make sure your interfaces are in promisc mode) 

Since you use heplify-server you can try to send protobuf instead hep. Use -protobuf

Heplify-server is listening for tls too so try to use TLS instead of UDP with -nt tls.

If nothing of this helps I will add some debug lines into the code.

**Comment by games130** [comment]
okay, so far around 24 hours have pass, no encounter for the missing packet. I am currently using:
./heplify -i p1p1 -vlan -dd=false &
./heplify -i p1p2 -vlan -dd=false &

Will let it run for a few more days before final confirmation. 
Do you want me to feedback anything as to why the deduplication might cause this?

other question, any performance improvement in using protobuf  vs HEP ?

**Comment by lmangani** [comment]
It would also be interesting to explore if Apache Arrow and its columnar in-memory layout could provide us with a long-term, global performance booster on both ends of the tunnel

**Comment by negbie** [comment]
I was already interested in this from second 1. Right now the Go implementation is far far away from useable for non numeric values but when it gets there I will evaluate it for sure.

**Comment by negbie** [comment]
Closing here because of no response.
