### ISSUE TITLE
How to configure syslog?

### ISSUE THREAD

**Issue by mihovilkolaric** [sipcapture/heplify#50]
The output of "heplify -h" (as well as the files logp/syslog*.go) imply that heplify supports syslog. 
Unfortunately the help-message does not give any information on how to enable or configure it, and (due to lacking "go"-skills) I was not able to find the answer in the sources.
How can I configure heplify to log to syslog instead of a file?

**Comment by negbie** [comment]
Hi, I patched it out some time ago to reduce one flag since the majority was OK with logging into the binary dir. Is it crucial for you?

**Comment by mihovilkolaric** [comment]
Hi,
thanks for the information.
I will need to use syslog - but if it is not supported natively, I guess I will find some workaround to pipe the logfile to syslog ...

**Comment by negbie** [comment]
If you are willing to compile it yourself you can put this inside main.go at line 64

	toSyslog := true
	config.Cfg.Logging.ToSyslog = &toSyslog

This will enable syslog output.

**Comment by negbie** [comment]
Closing here because of no response.

**Comment by mihovilkolaric** [comment]
Hi,

sorry for the late reply.
First of all: Thanks for the hint on how to re-enable syslog-support!
However, compiling myself is the last resort for me - I will rather stay at the workaround to feed the logfile to syslog.

**Comment by logock** [comment]
for the sake of completeness: use 'logger' to pipe the stdout to syslog, e.g. `/usr/bin/heplify -e 2>&1 | logger -t`

**Comment by negbie** [comment]
Thank you! Mby it could help others. If at least 2 or 3 more ppl want this I will simply include it ;)

**Comment by negbie** [comment]
FYI: since version 1.3 this can be activated via -sl flag

**Comment by AlexHeylin** [comment]
Thanks @negbie  :-)
