### ISSUE TITLE
Packets not fetched

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/heplify#52]
Hi,

I 'm running an Heplify instance on a Centos 7 and have some trouble to get full SIP packets to my heplify server.

The servers receives trafic miroring (cisco monitor session) from others servers / phones / sbc.

A lot of packets are missing (not present on '-l debug' nor in Hep capture ).

i've trued some tests but cannot go further on my own.

The last test i performed:  

`./heplify -hs 172.16.38.9:9060 -l debug -e  -i enp16s0f1  -vlan`

on a specific callflow i miss 40 packets on 41.

 I started a capture with similar arguments

`tcpdump -i enp16s0f1 portrange 5060-5090 -s0 -nn -w aaaaa.pcap`
 
An replayed it :
`./heplify -hs 172.16.38.9:9060 -rf aaaaa.pcap -l debug -e  -i enp16s0f1  -vlan`

I can see the all the needed packets on debug && HEP

I've tried to play with flags : -dd false , -t af_packet , -b   without benefit.

Have you any idea on what happens.

**Comment by negbie** [comment]
Could you please try it with -dd=false
Since it's a bool value -dd false won't work.

**Comment by negbie** [comment]
Is enp16s0f1 in promisc mode?

**Comment by dvillaume** [comment]
Not better with -dd=false.

I've tried in both promisc off//on whithout changes.

**Comment by negbie** [comment]
Would it be possible to send me a small sample pcap of your traffic to my private mail negbie@posteo.de?

**Comment by negbie** [comment]
You said "on a specific callflow i miss 40 packets on 41." To debug this better you can do following. Use the -fi flag to filter that specifiy callflow. -fi can take any string like a fromuser, ip. With this filter and -l debug -dd=false you should take a look on they layers output.

**Comment by dvillaume** [comment]
Sent on your mail.
I tried -fi before, but din't know it depended on -e

**Comment by negbie** [comment]
Hi,

-e is only for stdout output. It is undepended to all other flags.

Am 15.06.2018 16:40 schrieb dvillaume:
> Sent on your mail.
> I tried -fi before, but din't know it depended on -e

**Comment by negbie** [comment]
-e does not depend ony any flag. Its just to print to console.

**Comment by negbie** [comment]
Since it seems that your mentioned callflow is erspan encapsulated traffic could you please try the -erspan flag?

**Comment by dvillaume** [comment]
As seen together, not an erspan issue.
Finally bypassed wtith -t af_packet that issued in another problem broadworks call-id header format. 
Thanks to have pactch for broadworks Call-id header (V1.3)
