### ISSUE TITLE
Heplify 1.4 for Windows

### ISSUE THREAD

**Issue by Redis26** [sipcapture/heplify#65]
Hi, @negbie !
Please, build version 1.4 for Windows,
Tnx!

**Comment by negbie** [comment]
Hi @Redis26 ,
it's always a pain for me to build it for windows because I don't use it. Not at home, not at work. So I need to ask someone to gives me access for some minutes. I will see what I can do for you.

**Comment by Redis26** [comment]
If you want, I can compile heplify for Windows, give only the instruction ))

**Comment by negbie** [comment]
@Redis26 added to 1.4 release https://github.com/sipcapture/heplify/releases/tag/1.4

**Comment by kakamatyi** [comment]
Hi negbie, only 64 version, if you give me instuctions, or source code packege, I can compile a 32 bit version...
