### ISSUE TITLE
Not able to see any packets in Homer WEB UI

### ISSUE THREAD

**Issue by han-ish** [sipcapture/heplify#68]
I'm executing this command
$ ./heplify -rf succesFull.pcap -hs 127.0.0.1:9060 -t pcap -m SIP

I made sure that pcap has SIP packets, but no details are showing on  HOMER dashboard.
What could be the reason ?

**Comment by lmangani** [comment]
You're being too generic. We need to know what you installed and how in order to help you. Just as a starting note.. make sure you select a Time-Range in HOMER before searching.

**Comment by han-ish** [comment]
Yes. It was because of the date range. Thank you. Is there any way, after the install,  it will pick the current datetime ?

**Comment by lmangani** [comment]
@han-ish this is only a thing when you first install. Just remember this is a time-range based application and you need to first and foremost select the chunk of time you are interested into.

**Comment by han-ish** [comment]
Sure. Thank you for the quick response @lmangani
