### ISSUE TITLE
Win32 build

### ISSUE THREAD

**Issue by kakamatyi** [sipcapture/heplify#72]
Hi guys,
This is a great project!
I've tried to compile a 32 bit binary for win32 on both Linux and Windows, without success...
I'm new to go and missed some base libs fir win32...
Can you please release a 32 bit version of heplify.exe from latest release?
Thanks a lot!!!

**Comment by negbie** [comment]
Hi,
there are no plans to support win32 but from time to time you will find some win64 and linux 32 bit builds.
