### ISSUE TITLE
heplify not seeing any packet unless i run a parallel tcpdump

### ISSUE THREAD

**Issue by games130** [sipcapture/heplify#75]
As per title. if i run heplify by itself, i am getting 0 packets .
"./heplify -i RPG3 -pr 5060-7200 -vlan -dd=false -hi 2101 -hs 172.16.124.100:9060 -e -l debug"

```
2018/09/25 09:45:39.072345 util.go:116: INFO SIPCache EntryCount: 0, LookupCount: 0, HitCount: 0, ExpiredCount: 0, OverwriteCount: 0
2018/09/25 09:45:39.072423 util.go:122: INFO SDPCache EntryCount: 0, LookupCount: 0, HitCount: 0, ExpiredCount: 0, OverwriteCount: 0
2018/09/25 09:45:39.072489 util.go:128: INFO RTCPCache EntryCount: 0, LookupCount: 0, HitCount: 0, ExpiredCount: 0, OverwriteCount: 0
2018/09/25 09:45:39.072727 sniffer.go:395: INFO Stats {received dropped-os dropped-int}: {0 0 0}
2018/09/25 09:46:39.071986 util.go:110: INFO Packets since last minute IPv4: 0, IPv6: 0, UDP: 0, TCP: 0, RTCP: 0, RTCPFail: 0, DNS: 0, duplicate: 0, fragments: 0, unknown: 0
```

But once i have tcpdump running on the same interface "tcpdump -i RPG3 port 5060", i start to get packets on heplify as well.

```
2018/09/25 09:27:19.739551 publisher.go:53: INFO Packets since last minute sent: 130
2018/09/25 09:27:19.739616 util.go:111: INFO Packets since last minute IPv4: 130, IPv6: 0, UDP: 130, TCP: 0, RTCP: 0, RTCPFail: 0, DNS: 0, duplicate: 0, fragments: 0, unknown: 0
2018/09/25 09:27:19.739646 util.go:117: INFO SIPCache EntryCount: 0, LookupCount: 0, HitCount: 0, ExpiredCount: 0, OverwriteCount: 0
2018/09/25 09:27:19.739671 util.go:123: INFO SDPCache EntryCount: 0, LookupCount: 0, HitCount: 0, ExpiredCount: 0, OverwriteCount: 0
2018/09/25 09:27:19.739695 util.go:129: INFO RTCPCache EntryCount: 0, LookupCount: 0, HitCount: 0, ExpiredCount: 0, OverwriteCount: 0
2018/09/25 09:27:19.740271 sniffer.go:396: INFO Stats {received dropped-os dropped-int}: {130 0 0}

```

any idea what i can try to solve this?

**Comment by negbie** [comment]
Hi @games130,

heplify does not put the interface into promisc mode but tcpdump does. Simply check it with

netstat -i | grep RPG3

If you don't see a P there put the interface into promisc mode with

ip link set RPG3 promisc on

**Comment by negbie** [comment]
First of all you don't have to put the interface in promisc mode everytime. It depends on your network. But your explanation of the problem sounds like you need to put it in promisc mode on that machine.

Maybe netstat -i is not the best command to check. Could  you try it with

ip -d link show RPG3

If the interface is not in promisc mode you will find promiscuity 0 otherwise it's 1. If you use tcpdump you will see that if it runs promiscuity is set to 1 (enabled) and when you close tcpdump it's zero again.

You could also check this with 
dmesg -T

You should see this:
[Mi Sep 26 10:54:04 2018] device RPG3 entered promiscuous mode
[Mi Sep 26 10:54:11 2018] device RPG3 left promiscuous mode

I still think you did not put the interface correctly into promisc mode. What OS/Kernel do you use?

**Comment by games130** [comment]
These are the result:
I notice during the TCPdump there is this error "tcpdump: WARNING: RPG3: no IPv4 address assigned"

```
# ip link set RPG3 promisc on
# ip -d link show RPG3
15: RPG3: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN qlen 1000
    link/ether fa:16:3e:ef:91:6b brd ff:ff:ff:ff:ff:ff


# /usr/sbin/tcpdump -i RPG3 -v port 5060
tcpdump: WARNING: RPG3: no IPv4 address assigned
tcpdump: listening on RPG3, link-type EN10MB (Ethernet), capture size 65535 bytes

0 packets captured
0 packets received by filter
0 packets dropped by kernel

# dmesg | grep RPG3
ADDRCONF(NETDEV_UP): RPG3: link is not ready
8021q: adding VLAN 0 to HW filter on device RPG3
ADDRCONF(NETDEV_CHANGE): RPG3: link becomes ready
device RPG3 entered promiscuous mode
device RPG3 left promiscuous mode
device RPG3 entered promiscuous mode
device RPG3 left promiscuous mode
device RPG3 entered promiscuous mode
device RPG3 left promiscuous mode
device RPG3 entered promiscuous mode

```

Also the OS is a custom harden OS for running SBC. Just found out that when tcpdump is run, it actually point to a script which runs dcap together with tcpdump.

**Comment by negbie** [comment]
Hmm, could you please try out the heplify_nonstatic version? This does not include libpcap and should use the one from your os.

**Comment by negbie** [comment]
You could also play with -t af_packet if your os supports it.

**Comment by games130** [comment]
unfortunately both option does not work. I will just close this issue as i guess the problem is mainly due to the OS customization that prevent this capture.
