### ISSUE TITLE
32bit static build not possible because mdlayher/raw fails

### ISSUE THREAD

**Issue by vaizki** [sipcapture/heplify#77]
I need to build a static binary for an old 32bit debian-based linux SIP proxy but the docker builder is failing:

Cloned master from this repo and:
`# docker run --rm=true -itv $PWD:/mnt i386/alpine:3.8 /mnt/build_static.sh`

Relevant errors:
```
# github.com/mdlayher/raw
../../mdlayher/raw/raw_linux.go:316:32: undefined: syscall.SYS_GETSOCKOPT
../../mdlayher/raw/raw_linux.go:329:32: undefined: syscall.SYS_SETSOCKOPT
../../mdlayher/raw/timeval.go:17:6: cannot use int64(timeout / time.Second) (type int64) as type int32 in field value
../../mdlayher/raw/timeval.go:18:7: cannot use int64(timeout % time.Second / time.Microsecond) (type int64) as type int32 in field value

```

I am not versant in Go yet, should we vendor in some packages or just complain upstream?

Full log at:  https://gist.github.com/vaizki/baac8cb55ba1b6647843c0b964f78c72

**Comment by negbie** [comment]
Hi,

thank you for the report. I guess it's time to start vendoring anyway so I will address this when I'm back from astricon. If you don't want to wait you could play around with go's 1.11 modules or report it upstream.

**Comment by vaizki** [comment]
After investigating further, I reported it as an issue upstream, https://github.com/mdlayher/raw/issues/31 and I found other packages also reporting similar build issues as this is a dependency for google/gopacket which is pretty popular.

It should be an easy fix with build constraints and splitting the statistics syscalls into separate files. So easy in fact that I may be able to learn the Go build environent fast enough to fix it.

**Comment by vaizki** [comment]
After giving it a rough bash and getting the packet capture going, I seem to have triggered a SEGV in the packet decoding. I am close to declaring this a dead end and doing port mirroring :)

```
2018/10/11 13:38:20.233896 decoder.go:174: DBG [layer]
[Linux SLL IPv4]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8115e2c]

goroutine 1 [running]:
panic(0x84832e0, 0x97812008)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x331
sync/atomic.AddUint64(0x978401fc, 0x1, 0x0, 0x3, 0x9cd05d24)
        /usr/lib/go-1.7/src/sync/atomic/asm_386.s:112 +0xc
github.com/negbie/heplify/decoder.(*Decoder).Process(0x978401b0, 0x97862000, 0x5ec, 0x5ec, 0x977fe1e0)
        /go/src/github.com/negbie/heplify/decoder/decoder.go:198 +0x67c
github.com/negbie/heplify/sniffer.(*MainWorker).OnPacket(0x97812380, 0x97862000, 0x5ec, 0x5ec, 0x977fe1e0)
        /go/src/github.com/negbie/heplify/sniffer/sniffer.go:77 +0x44
github.com/negbie/heplify/sniffer.(*SnifferSetup).Run(0x978ba0c0, 0x0, 0x0)
        /go/src/github.com/negbie/heplify/sniffer/sniffer.go:320 +0x976
main.main()
        /go/src/github.com/negbie/heplify/main.go:110 +0xca
``´

**Comment by negbie** [comment]
Don't get frustrated. I will help you as soon as possible.

**Comment by negbie** [comment]
@vaizki I just pushed a patch to use the right memory alignment for i386. This should fix your latest segfault. If you want to know more about it I would read this:
https://go101.org/article/memory-layout.html

Nevertheless you still have to use conditional compilation or uncomment in sniffer/sniffer.go everything with dumpPcap() and dumpChan + delete the file sniffer/pcap.go

I use pcapgo (which uses mdlayher/raw) to write packet into a pcap file. If you don't use this feature which heplify provides with the -wf file you can delete it like mentioned above.

**Comment by negbie** [comment]
@vaizki I just pushed some changes to remove mdlayher/raw dependency without losing any functionality. I published a 32bit linux version too under releases.

**Comment by vaizki** [comment]
Thank you @negbie the patch seems to work fine and I am able to capture traffic from the old proxy now. I did an ugly conditional compilation hack on the mdlayher/raw lib to do that. 

I am not 100% sure everything works yet because I am not seeing a large portion of the traffic in my heplify-server + homer + influxdb stack but it may be because we get a LOT of  INVITEs which are larger than the MTU so UDP packets get fragmented. Also some network scanners are probably causing the Homer DB or UI to freak out. I need to investigate a more robust stack.

**Comment by negbie** [comment]
@vaizki happy to help. I love it when users have some bigger setup's with a lot of traffic. Above 10k pps things become interesting.

Heplify can handle fragmented packets and will reassemble them. You can see it in action with the flag "-d fragment".

If you have some more news tell me ;)

**Comment by vaizki** [comment]
Well mdlayher just merged a patch to fix the i386 build so now with your alignment fixes the 32bit static binary builds out of the box with build_static.sh. Thanks!

I will have time next week to look into this more but even when capturing on a test node with very little traffic but big 2kB INVITEs we're just not seeing many of the transactions in Homer. So I will try to find out where in the chain of pcap->heplify->heplify-server->mysql->homer->browser they get lost and take it up in the appropriate forum. This is the first time I'm using Homer so might be something really simple to fix...

**Comment by negbie** [comment]
@vaizki Cool! Thank you for your contribution! This does not only help me but many others which are using the pcapgo package.

About your issue. We will handle it! Just open a new issue with your findings and I will take a look on it. You can also send me a pcap to my private email address so I can test it.
