### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by mikekovacevic** [sipcapture/heplify#81]
Re-opening from https://github.com/sipcapture/heplify-server/issues/139

I've been trying to mirror SIP TCP traffic via heplify through heplify-server and have some issues processing TCP packets. I'm using heplify-server 0.96. For context, we're using OpenSIPS as a SIP Proxy to convert from a WebSocket (which end-user clients are using via a load balancer) to SIP over UDP. It seems that the TCP traffic is being mirrored via heplify, however is not being inserted into HOMER properly via heplify-server. I've attached a few items from my debugging and would appreciate some help:

[webrtc_capture.zip](https://github.com/sipcapture/heplify-server/files/2573390/webrtc_capture.zip)

- Interface capture at OpenSIPS showing both TCP/UDP traffic (interface.pcap) (this is then mirrored over TLS from heplify to heplify-server)
- Resulting HOMER PCAP (includes messages from other parts of our infrastructure) showing that the TCP SIP messages are missing
- The heplify-server.log showing warnings with malformed packets
- The configuration of heplify-server

Please let me know if there's anything else I can attach to help with debugging.

**Comment by negbie** [comment]
Hi @mikekovacevic,
ok I understand your setup from the pcap. Some things you need to know. You have to run heplify with -tcpassembly flag but it's still in beta stage and needs some improvements. I tested it with some TCP pcaps from heplify's example folder but I will have a look into your pcap aswell.

**Comment by negbie** [comment]
Something else I noticed is that I don't handle the Websocket header (81 7e 01 7d) before the SIP message. This is why tcpassembly does not work in this case because it does not detect this packet as SIP packet because of the Websocket bytes.

**Comment by negbie** [comment]
So right now there is no support for capturing packets over Websockets.

**Comment by mikekovacevic** [comment]
Ok we'll have to find another workaround in the meantime then to add tracing. 

I had another question about this (and let me know if you'd like me to open another issue for it) but would the lack of processing this type of INVITE impact RTCP correlation then? I've noticed for these calls that RTCP is not being forwarded properly either via the heplify agent

**Comment by negbie** [comment]
Well, this should work BUT websockets can use something called masking_key which masks the payload. So the rtcp correlator does not see the plain SIP message. You can see this in your pcap for a INVITE over websocket.

**Comment by negbie** [comment]
Keep in mind that wireshark has the masking_key handling implemented so at the bottom you can see the plain SIP message.

**Comment by negbie** [comment]
Hi @mikekovacevic,
this week I want to implement some features based on websockets so I needed it in heplify. I added it today and tested it with your provided pcap without issues. Just use the -tcpassembly flag.
