### ISSUE TITLE
Missing packets when high traffic

### ISSUE THREAD

**Issue by hdtri** [sipcapture/heplify#86]
Hi all,

I'm using heplify ver 1.46 and heplify always missing packets at peak time (SPAN traffic ~ 300Mb/s).

./heplify -i eth0 -hs X.X.X.X:9060 -m SIP -dim OPTIONS,NOTIFY,REGISTER,SUBSCRIBE

Anybody have the same issue?
Thank you

**Comment by hdtri** [comment]
Attach picture
![image](https://user-images.githubusercontent.com/23566155/48936784-8731d180-ef3e-11e8-821f-098e3fc7befb.png)

**Comment by negbie** [comment]
Please try to run it with 
./heplify -i eth0 -hs X.X.X.X:9060 -m SIP -dim OPTIONS,NOTIFY,REGISTER,SUBSCRIBE -t af_packet

**Comment by negbie** [comment]
Make sure the interface you are sniffing on has no packet drops.

**Comment by hdtri** [comment]
I've tried above command and got this problems
Critical: setting af_packet handle: no known tpacket versions work on this machine

How i can install tpacket?

**Comment by hdtri** [comment]
>  no packet drops.

Yes, I'm sure, because I use tshark and captured fully packets

**Comment by negbie** [comment]
Your OS has no af_packet support. I've uploaded a nonstatic 1.46 version. This should be a little bit faster than the static version. But I guess the best way would be to use a non legacy OS which has af_packet support.

**Comment by negbie** [comment]
Some other things. How do you make sure that the packets are lost during capturing and not between heplify and the capture server? You run tshark and heplify with -wf flag only and compared the pcaps? Maybe you should try to use TCP between heplify and the capture server.

**Comment by negbie** [comment]
Close due to no response.

**Comment by khorsmann** [comment]
@negbie  - for nostiagic reasions and i used two old systems - where can i found the static version?

**Comment by negbie** [comment]
@khorsmann sorry I forgot to reply to your question. I made a special nonstatic version for hdtri here https://github.com/sipcapture/heplify/releases/tag/1.46 with the suffix _nonstatic. The one without suffix should be static, isn't it? If so mby sipcapture folks can build a new version for you.
