### ISSUE TITLE
Centos 6  X32 cant use

### ISSUE THREAD

**Issue by gudge25** [sipcapture/heplify#9]
Cant use   heplify  because it is compilled to X64 
when i want to create   fille from tar :

[root@goip16 heplify-0.85]# make
go build -ldflags "-s -w"  -o heplify *.go
main.go:9:2: cannot find package "github.com/negbie/heplify/config" in any of:
        /usr/lib/golang/src/github.com/negbie/heplify/config (from $GOROOT)
        ($GOPATH not set)
main.go:10:2: cannot find package "github.com/negbie/heplify/logp" in any of:
        /usr/lib/golang/src/github.com/negbie/heplify/logp (from $GOROOT)
        ($GOPATH not set)
main.go:11:2: cannot find package "github.com/negbie/heplify/sniffer" in any of:
        /usr/lib/golang/src/github.com/negbie/heplify/sniffer (from $GOROOT)
        ($GOPATH not set)
make: *** [all] Error 1

**Comment by gudge25** [comment]
ok maybe i am doing something wrong

**Comment by negbie** [comment]
Did you try to

set GOARCH=386  

before compile?

**Comment by negbie** [comment]
Oh and I see I have only the build command in the makefile ;) So you need to do

go get -d -v -u github.com/negbie/heplify

**Comment by negbie** [comment]
But this is a good reminder to build a 32 bit binary too ;)

**Comment by gudge25** [comment]
:) GREAT IDEA   
because make  is not working 

[root@goip16 heplify-0.85]# make all
go build -ldflags "-s -w"  -o heplify *.go
# github.com/google/gopacket/afpacket
could not determine kind of name for C.sizeof_struct_tpacket3_hdr
make: *** [all] Error 2

**Comment by negbie** [comment]
Ok seems there is a bug in the /google/gopacket/afpacket source. Will open a ticket later at googles gopacket repo. Anyway I will make a static 386 build in a few minutes.

**Comment by negbie** [comment]
Ok made the binary
https://github.com/sipcapture/heplify/releases/download/0.9/heplify386

**Comment by gudge25** [comment]
MANY  THANKS :) :+1:

**Comment by negbie** [comment]
Your  welcome. Please tell me if everything works since i neither tested it on centos nor on i386
