### ISSUE TITLE
Heplify crashes 

### ISSUE THREAD

**Issue by pnlsantos** [sipcapture/heplify#97]
hi heplify client still crashes after some time 
os: centOS 6.0
heplify 1.46

dump : 

2018/12/08 09:56:03.806184 sniffer.go:391: INFO Stats {received dropped-os dropped-int}: {34907978 0 0}
2018/12/08 09:56:04.283982 publisher.go:54: INFO Packets since last minute sent: 15
panic: runtime error: index out of range

goroutine 1 [running]:
encoding/binary.binary.bigEndian.Uint16(...)
        /usr/lib/go/src/encoding/binary/binary.go:100
github.com/negbie/heplify/protos.ParseRTCP(0xc42587a02c, 0x6b, 0x6b, 0x4b, 0xc425797570, 0x5, 0x5, 0x7fd56fd5e240, 0xc42002e4e0, 0xc4267bce00, ...)
        /go/src/github.com/negbie/heplify/protos/rtcp.go:210 +0x2431
github.com/negbie/heplify/decoder.correlateRTCP(0xc42587a01c, 0x4, 0x7b, 0x151d, 0xc42587a020, 0x4, 0x77, 0x5c87fd56f62151d, 0xc42587a02c, 0x6b, ...)
        /go/src/github.com/negbie/heplify/decoder/correlator.go:93 +0x5f
github.com/negbie/heplify/decoder.(*Decoder).processTransport(0xc4255380c0, 0x7fd56ff75210, 0x7fd56ff76000, 0x7fd56ff76560, 0x1, 0x4, 0x4, 0xfdc7c70a, 0x0, 0xfdc7c70a, ...)
        /go/src/github.com/negbie/heplify/decoder/decoder.go:315 +0x8ad
github.com/negbie/heplify/decoder.(*Decoder).Process(0xc4255380c0, 0xc42587a000, 0x97, 0x97, 0xc420dcda40)
        /go/src/github.com/negbie/heplify/decoder/decoder.go:211 +0xc32
github.com/negbie/heplify/sniffer.(*MainWorker).OnPacket(0xc42002e8b0, 0xc42587a000, 0x97, 0x97, 0xc420dcda40)
        /go/src/github.com/negbie/heplify/sniffer/sniffer.go:73 +0x59
github.com/negbie/heplify/sniffer.(*SnifferSetup).Run(0xc4201288f0, 0x7fd56fd5c5a0, 0xc4201288f0)
        /go/src/github.com/negbie/heplify/sniffer/sniffer.go:316 +0x5f9
main.main()
        /go/src/github.com/negbie/heplify/main.go:110 +0xde
You have new mail in /var/spool/mail/root

**Comment by negbie** [comment]
Hi @pnlsantos 
thank you for the report. Some days ago I found during automated fuzzing a bug in ParseRTCP which seems to be the one you have. I fixed it and just published version 1.47 under releases.

**Comment by negbie** [comment]
@pnlsantos I guess I can close this?
